(assert '(hasClassName "elements class*" "elements"))
(assert '(hasClassMemberName "elements class*" "element"))

;;; class names
 
 (assert '(hasClassName "metal class*" "metals"))
 (assert '(hasClassMemberName "metal class*" "metal"))
 (assert '(hasClassName "semi-metal class*" "semi-metals"))
 (assert '(hasClassMemberName "semi-metal class*" "semi-metal"))
 (assert '(hasClassName "non-metal class*" "non-metals"))
 (assert '(hasClassMemberName "non-metal class*" "non-metal"))
 ;;; element isas
 (assert '(Isa "hydrogen element*" "element class*"))
 (assert '(Isa "helium element*" "element class*"))
 (assert '(Isa "lithium element*" "element class*"))
 (assert '(Isa "beryllium element*" "element class*"))
 (assert '(Isa "boron element*" "element class*"))
 (assert '(Isa "carbon element*" "element class*"))
 (assert '(Isa "nitrogen element*" "element class*"))
 (assert '(Isa "oxygen element*" "element class*"))
 (assert '(Isa "fluorine element*" "element class*"))
 (assert '(Isa "neon element*" "element class*"))
 (assert '(Isa "sodium element*" "element class*"))
 (assert '(Isa "magnesium element*" "element class*"))
 (assert '(Isa "aluminium element*" "element class*"))
 (assert '(Isa "silicon element*" "element class*"))
 (assert '(Isa "phosphorus element*" "element class*"))
 (assert '(Isa "sulfur element*" "element class*"))
 (assert '(Isa "chlorine element*" "element class*"))
 (assert '(Isa "argon element*" "element class*"))
 (assert '(Isa "potassium element*" "element class*"))
 (assert '(Isa "calcium element*" "element class*"))
 (assert '(Isa "scandium element*" "element class*"))
 (assert '(Isa "titanium element*" "element class*"))
 (assert '(Isa "vanadium element*" "element class*"))
 (assert '(Isa "chromium element*" "element class*"))
 (assert '(Isa "manganese  element*" "element class*"))
 (assert '(Isa "iron element*" "element class*"))
 (assert '(Isa "cobalt element*" "element class*"))
 (assert '(Isa "nickel element*" "element class*"))
 (assert '(Isa "copper element*" "element class*"))
 (assert '(Isa "zinc element*" "element class*"))
 (assert '(Isa "gallium element*" "element class*"))
 (assert '(Isa "germanium element*" "element class*"))
 (assert '(Isa "arsenic element*" "element class*"))
 (assert '(Isa "selenium element*" "element class*"))
 (assert '(Isa "bromine element*" "element class*"))
 (assert '(Isa "krypton element*" "element class*"))
 (assert '(Isa "rubidium element*" "element class*"))
 (assert '(Isa "strontium element*" "element class*"))
 (assert '(Isa "yttrium element*" "element class*"))
 (assert '(Isa "zirconium element*" "element class*"))
 (assert '(Isa "niobium element*" "element class*"))
 (assert '(Isa "molybdenum element*" "element class*"))
 (assert '(Isa "technetium element*" "element class*"))
 (assert '(Isa "ruthenium element*" "element class*"))
 (assert '(Isa "rhodium element*" "element class*"))
 (assert '(Isa "palladium element*" "element class*"))
 (assert '(Isa "silver element*" "element class*"))
 (assert '(Isa "cadmium element*" "element class*"))
 (assert '(Isa "indium element*" "element class*"))
 (assert '(Isa "tin element*" "element class*"))
 (assert '(Isa "antimony element*" "element class*"))
 (assert '(Isa "tellurium element*" "element class*"))
 (assert '(Isa "iodine element*" "element class*"))
 (assert '(Isa "xenon element*" "element class*"))
 (assert '(Isa "caesium element*" "element class*"))
 (assert '(Isa "barium element*" "element class*"))
 (assert '(Isa "lanthanum element*" "element class*"))
 (assert '(Isa "cerium element*" "element class*"))
 (assert '(Isa "praseodymium element*" "element class*"))
 (assert '(Isa "neodymium element*" "element class*"))
 (assert '(Isa "promethium element*" "element class*"))
 (assert '(Isa "samarium element*" "element class*"))
 (assert '(Isa "europium element*" "element class*"))
 (assert '(Isa "gadolinium element*" "element class*"))
 (assert '(Isa "terbium element*" "element class*"))
 (assert '(Isa "dysprosium element*" "element class*"))
 (assert '(Isa "holmium element*" "element class*"))
 (assert '(Isa "erbium element*" "element class*"))
 (assert '(Isa "thulium element*" "element class*"))
 (assert '(Isa "ytterbium element*" "element class*"))
 (assert '(Isa "lutetium element*" "element class*"))
 (assert '(Isa "hafnium element*" "element class*"))
 (assert '(Isa "tantalum element*" "element class*"))
 (assert '(Isa "tungsten element*" "element class*"))
 (assert '(Isa "rhenium element*" "element class*"))
 (assert '(Isa "osmium element*" "element class*"))
 (assert '(Isa "iridium element*" "element class*"))
 (assert '(Isa "platinum element*" "element class*"))
 (assert '(Isa "gold element*" "element class*"))
 (assert '(Isa "mercury element*" "element class*"))
 (assert '(Isa "thallium element*" "element class*"))
 (assert '(Isa "lead element*" "element class*"))
 (assert '(Isa "bismuth element*" "element class*"))
 (assert '(Isa "polonium element*" "element class*"))
 (assert '(Isa "astatine element*" "element class*"))
 (assert '(Isa "radon element*" "element class*"))
 (assert '(Isa "francium element*" "element class*"))
 (assert '(Isa "radium element*" "element class*"))
 (assert '(Isa "actinium element*" "element class*"))
 (assert '(Isa "thorium element*" "element class*"))
 (assert '(Isa "protactinium element*" "element class*"))
 (assert '(Isa "uranium element*" "element class*"))
 (assert '(Isa "neptunium element*" "element class*"))
 (assert '(Isa "plutonium element*" "element class*"))
 (assert '(Isa "americium element*" "element class*"))
 (assert '(Isa "curium element*" "element class*"))
 (assert '(Isa "berkelium element*" "element class*"))
 (assert '(Isa "californium element*" "element class*"))
 (assert '(Isa "einsteinium element*" "element class*"))
 (assert '(Isa "fermium element*" "element class*"))
 (assert '(Isa "mendelevium element*" "element class*"))
 (assert '(Isa "nobelium element*" "element class*"))
 (assert '(Isa "lawrencium element*" "element class*"))
 (assert '(Isa "rutherfordium element*" "element class*"))
 (assert '(Isa "dubnium element*" "element class*"))
 (assert '(Isa "seaborgium element*" "element class*"))
 (assert '(Isa "bohrium element*" "element class*"))
 (assert '(Isa "hassium element*" "element class*"))
 (assert '(Isa "meitnerium element*" "element class*"))
 (assert '(Isa "darmstadtium element*" "element class*"))
 (assert '(Isa "roentgenium  element*" "element class*"))
 (assert '(Isa "copernicium element*" "element class*"))
 (assert '(Isa "ununtrium element*" "element class*"))
 (assert '(Isa "flerovium element*" "element class*"))
 (assert '(Isa "ununpentium element*" "element class*"))
 (assert '(Isa "livermorium element*" "element class*"))
 (assert '(Isa "ununseptium element*" "element class*"))
 (assert '(Isa "ununoctium element*" "element class*"))
 ;;; element names
 (assert '(hasElementName "hydrogen element*" "hydrogen"))
 (assert '(hasElementName "helium element*" "helium"))
 (assert '(hasElementName "lithium element*" "lithium"))
 (assert '(hasElementName "beryllium element*" "beryllium"))
 (assert '(hasElementName "boron element*" "boron"))
 (assert '(hasElementName "carbon element*" "carbon"))
 (assert '(hasElementName "nitrogen element*" "nitrogen"))
 (assert '(hasElementName "oxygen element*" "oxygen"))
 (assert '(hasElementName "fluorine element*" "fluorine"))
 (assert '(hasElementName "neon element*" "neon"))
 (assert '(hasElementName "sodium element*" "sodium"))
 (assert '(hasElementName "magnesium element*" "magnesium"))
 (assert '(hasElementName "aluminium element*" "aluminium"))
 (assert '(hasElementName "silicon element*" "silicon"))
 (assert '(hasElementName "phosphorus element*" "phosphorus"))
 (assert '(hasElementName "sulfur element*" "sulfur"))
 (assert '(hasElementName "chlorine element*" "chlorine"))
 (assert '(hasElementName "argon element*" "argon"))
 (assert '(hasElementName "potassium element*" "potassium"))
 (assert '(hasElementName "calcium element*" "calcium"))
 (assert '(hasElementName "scandium element*" "scandium"))
 (assert '(hasElementName "titanium element*" "titanium"))
 (assert '(hasElementName "vanadium element*" "vanadium"))
 (assert '(hasElementName "chromium element*" "chromium"))
 (assert '(hasElementName "manganese element*" "manganese"))
 (assert '(hasElementName "iron element*" "iron"))
 (assert '(hasElementName "cobalt element*" "cobalt"))
 (assert '(hasElementName "nickel element*" "nickel"))
 (assert '(hasElementName "copper element*" "copper"))
 (assert '(hasElementName "zinc element*" "zinc"))
 (assert '(hasElementName "gallium element*" "gallium"))
 (assert '(hasElementName "germanium element*" "germanium"))
 (assert '(hasElementName "arsenic element*" "arsenic"))
 (assert '(hasElementName "selenium element*" "selenium"))
 (assert '(hasElementName "bromine element*" "bromine"))
 (assert '(hasElementName "krypton element*" "krypton"))
 (assert '(hasElementName "rubidium element*" "rubidium"))
 (assert '(hasElementName "strontium element*" "strontium"))
 (assert '(hasElementName "yttrium element*" "yttrium"))
 (assert '(hasElementName "zirconium element*" "zirconium"))
 (assert '(hasElementName "niobium element*" "niobium"))
 (assert '(hasElementName "molybdenum element*" "molybdenum"))
 (assert '(hasElementName "technetium element*" "technetium"))
 (assert '(hasElementName "ruthenium element*" "ruthenium"))
 (assert '(hasElementName "rhodium element*" "rhodium"))
 (assert '(hasElementName "palladium element*" "palladium"))
 (assert '(hasElementName "silver element*" "silver"))
 (assert '(hasElementName "cadmium element*" "cadmium"))
 (assert '(hasElementName "indium element*" "indium"))
 (assert '(hasElementName "tin element*" "tin"))
 (assert '(hasElementName "antimony element*" "antimony"))
 (assert '(hasElementName "tellurium element*" "tellurium"))
 (assert '(hasElementName "iodine element*" "iodine"))
 (assert '(hasElementName "xenon element*" "xenon"))
 (assert '(hasElementName "caesium element*" "caesium"))
 (assert '(hasElementName "barium element*" "barium"))
 (assert '(hasElementName "lanthanum element*" "lanthanum"))
 (assert '(hasElementName "cerium element*" "cerium"))
 (assert '(hasElementName "praseodymium element*" "praseodymium"))
 (assert '(hasElementName "neodymium element*" "neodymium"))
 (assert '(hasElementName "promethium element*" "promethium"))
 (assert '(hasElementName "samarium element*" "samarium"))
 (assert '(hasElementName "europium element*" "europium"))
 (assert '(hasElementName "gadolinium element*" "gadolinium"))
 (assert '(hasElementName "terbium element*" "terbium"))
 (assert '(hasElementName "dysprosium element*" "dysprosium"))
 (assert '(hasElementName "holmium element*" "holmium"))
 (assert '(hasElementName "erbium element*" "erbium"))
 (assert '(hasElementName "thulium element*" "thulium"))
 (assert '(hasElementName "ytterbium element*" "ytterbium"))
 (assert '(hasElementName "lutetium element*" "lutetium"))
 (assert '(hasElementName "hafnium element*" "hafnium"))
 (assert '(hasElementName "tantalum element*" "tantalum"))
 (assert '(hasElementName "tungsten element*" "tungsten"))
 (assert '(hasElementName "rhenium element*" "rhenium"))
 (assert '(hasElementName "osmium element*" "osmium"))
 (assert '(hasElementName "iridium element*" "iridium"))
 (assert '(hasElementName "platinum element*" "platinum"))
 (assert '(hasElementName "gold element*" "gold"))
 (assert '(hasElementName "mercury element*" "mercury"))
 (assert '(hasElementName "thallium element*" "thallium"))
 (assert '(hasElementName "lead element*" "lead"))
 (assert '(hasElementName "bismuth element*" "bismuth"))
 (assert '(hasElementName "polonium element*" "polonium"))
 (assert '(hasElementName "astatine element*" "astatine"))
 (assert '(hasElementName "radon element*" "radon"))
 (assert '(hasElementName "francium element*" "francium"))
 (assert '(hasElementName "radium element*" "radium"))
 (assert '(hasElementName "actinium element*" "actinium"))
 (assert '(hasElementName "thorium element*" "thorium"))
 (assert '(hasElementName "protactinium element*" "protactinium"))
 (assert '(hasElementName "uranium element*" "uranium"))
 (assert '(hasElementName "neptunium element*" "neptunium"))
 (assert '(hasElementName "plutonium element*" "plutonium"))
 (assert '(hasElementName "americium element*" "americium"))
 (assert '(hasElementName "curium element*" "curium"))
 (assert '(hasElementName "berkelium element*" "berkelium"))
 (assert '(hasElementName "californium element*" "californium"))
 (assert '(hasElementName "einsteinium element*" "einsteinium"))
 (assert '(hasElementName "fermium element*" "fermium"))
 (assert '(hasElementName "mendelevium element*" "mendelevium"))
 (assert '(hasElementName "nobelium element*" "nobelium"))
 (assert '(hasElementName "lawrencium element*" "lawrencium"))
 (assert '(hasElementName "rutherfordium element*" "rutherfordium"))
 (assert '(hasElementName "dubnium element*" "dubnium"))
 (assert '(hasElementName "seaborgium element*" "seaborgium"))
 (assert '(hasElementName "bohrium element*" "bohrium"))
 (assert '(hasElementName "hassium element*" "hassium"))
 (assert '(hasElementName "meitnerium element*" "meitnerium"))
 (assert '(hasElementName "darmstadtium element*" "darmstadtium"))
 (assert '(hasElementName "roentgenium  element*" "roentgenium"))
 (assert '(hasElementName "copernicium element*" "copernicium"))
 (assert '(hasElementName "ununtrium element*" "ununtrium"))
 (assert '(hasElementName "flerovium element*" "flerovium"))
 (assert '(hasElementName "ununpentium element*" "ununpentium"))
 (assert '(hasElementName "livermorium element*" "livermorium"))
 (assert '(hasElementName "ununseptium element*" "ununseptium"))
 (assert '(hasElementName "ununoctium element*" "ununoctium"))
 ;;; element symbols
 (assert '(hasSymbol "hydrogen element*" "H"))
 (assert '(hasSymbol "helium element*" "He"))
 (assert '(hasSymbol "lithium element*" "Li"))
 (assert '(hasSymbol "beryllium element*" "Be"))
 (assert '(hasSymbol "boron element*" "B"))
 (assert '(hasSymbol "carbon element*" "C"))
 (assert '(hasSymbol "nitrogen element*" "N"))
 (assert '(hasSymbol "oxygen element*" "O"))
 (assert '(hasSymbol "fluorine element*" "F"))
 (assert '(hasSymbol "neon element*" "Ne"))
 (assert '(hasSymbol "sodium element*" "Na"))
 (assert '(hasSymbol "magnesium element*" "Mg"))
 (assert '(hasSymbol "aluminium element*" "Al"))
 (assert '(hasSymbol "silicon element*" "Si"))
 (assert '(hasSymbol "phosphorus element*" "P"))
 (assert '(hasSymbol "sulfur element*" "S"))
 (assert '(hasSymbol "chlorine element*" "Cl"))
 (assert '(hasSymbol "argon element*" "Ar"))
 (assert '(hasSymbol "potassium element*" "K"))
 (assert '(hasSymbol "calcium element*" "Ca"))
 (assert '(hasSymbol "scandium element*" "Sc"))
 (assert '(hasSymbol "titanium element*" "Ti"))
 (assert '(hasSymbol "vanadium element*" "V"))
 (assert '(hasSymbol "chromium element*" "Cr"))
 (assert '(hasSymbol "manganese  element*" "Mn"))
 (assert '(hasSymbol "iron element*" "Fe"))
 (assert '(hasSymbol "cobalt element*" "Co"))
 (assert '(hasSymbol "nickel element*" "Ni"))
 (assert '(hasSymbol "copper element*" "Cu"))
 (assert '(hasSymbol "zinc element*" "Zn"))
 (assert '(hasSymbol "gallium element*" "Ga"))
 (assert '(hasSymbol "germanium element*" "Ge"))
 (assert '(hasSymbol "arsenic element*" "As"))
 (assert '(hasSymbol "selenium element*" "Se"))
 (assert '(hasSymbol "bromine element*" "Br"))
 (assert '(hasSymbol "krypton element*" "Kr"))
 (assert '(hasSymbol "rubidium element*" "Rb"))
 (assert '(hasSymbol "strontium element*" "Sr"))
 (assert '(hasSymbol "yttrium element*" "Y"))
 (assert '(hasSymbol "zirconium element*" "Zr"))
 (assert '(hasSymbol "niobium element*" "Nb"))
 (assert '(hasSymbol "molybdenum element*" "Mo"))
 (assert '(hasSymbol "technetium element*" "Tc"))
 (assert '(hasSymbol "ruthenium element*" "Ru"))
 (assert '(hasSymbol "rhodium element*" "Rh"))
 (assert '(hasSymbol "palladium element*" "Pd"))
 (assert '(hasSymbol "silver element*" "Ag"))
 (assert '(hasSymbol "cadmium element*" "Cd"))
 (assert '(hasSymbol "indium element*" "In"))
 (assert '(hasSymbol "tin element*" "Sn"))
 (assert '(hasSymbol "antimony element*" "Sb"))
 (assert '(hasSymbol "tellurium element*" "Te"))
 (assert '(hasSymbol "iodine element*" "I"))
 (assert '(hasSymbol "xenon element*" "Xe"))
 (assert '(hasSymbol "caesium element*" "Cs"))
 (assert '(hasSymbol "barium element*" "Ba"))
 (assert '(hasSymbol "lanthanum element*" "La"))
 (assert '(hasSymbol "hafnium element*" "Hf"))
 (assert '(hasSymbol "tantalum element*" "Ta"))
 (assert '(hasSymbol "tungsten element*" "W"))
 (assert '(hasSymbol "rhenium element*" "Re"))
 (assert '(hasSymbol "osmium element*" "Os"))
 (assert '(hasSymbol "iridium element*" "Ir"))
 (assert '(hasSymbol "platinum element*" "Pt"))
 (assert '(hasSymbol "gold element*" "Au"))
 (assert '(hasSymbol "mercury element*" "Hg"))
 (assert '(hasSymbol "thallium element*" "Tl"))
 (assert '(hasSymbol "lead element*" "Pb"))
 (assert '(hasSymbol "bismuth element*" "Bi"))
 (assert '(hasSymbol "astatine element*" "At"))
 (assert '(hasSymbol "radon element*" "Rn"))
 (assert '(hasSymbol "francium element*" "Fr"))
 (assert '(hasSymbol "radium element*" "Ra"))
 (assert '(hasSymbol "actinium element*" "Ac"))
 (assert '(hasSymbol "cerium element*" "Ce"))
 (assert '(hasSymbol "praseodymium element*" "Pr"))
 (assert '(hasSymbol "neodymium element*" "Nd"))
 (assert '(hasSymbol "promethium element*" "Pm"))
 (assert '(hasSymbol "samarium element*" "Sm"))
 (assert '(hasSymbol "europium element*" "Eu"))
 (assert '(hasSymbol "gadolinium element*" "Gd"))
 (assert '(hasSymbol "terbium element*" "Tb"))
 (assert '(hasSymbol "dysprosium element*" "Dy"))
 (assert '(hasSymbol "holmium element*" "Ho"))
 (assert '(hasSymbol "erbium element*" "Er"))
 (assert '(hasSymbol "thulium element*" "Tm"))
 (assert '(hasSymbol "ytterbium element*" "Yb"))
 (assert '(hasSymbol "thorium element*" "Th"))
 (assert '(hasSymbol "protactinium element*" "Pa"))
 (assert '(hasSymbol "uranium element*" "U"))
 (assert '(hasSymbol "neptunium element*" "Np"))
 (assert '(hasSymbol "plutonium element*" "Pu"))
 (assert '(hasSymbol "americium element*" "Am"))
 (assert '(hasSymbol "curium element*" "Cm"))
 (assert '(hasSymbol "berkelium element*" "Bk"))
 (assert '(hasSymbol "californium element*" "Cf"))
 (assert '(hasSymbol "einsteinium element*" "Es"))
 (assert '(hasSymbol "fermium element*" "Fm"))
 (assert '(hasSymbol "mendelevium element*" "Md"))
 (assert '(hasSymbol "lawrencium element*" "Lr"))
 (assert '(hasSymbol "rutherfordium element*" "Rf"))
 (assert '(hasSymbol "dubnium element*" "Db"))
 (assert '(hasSymbol "seaborgium element*" "Sg"))
 (assert '(hasSymbol "bohrium element*" "Bh"))
 (assert '(hasSymbol "hassium element*" "Hs"))
 (assert '(hasSymbol "meitnerium element*" "Mt"))
 (assert '(hasSymbol "darmstadtium element*" "Ds"))
 (assert '(hasSymbol "roentgenium  element*" "Rg"))
 (assert '(hasSymbol "copernicium element*" "Cn"))
 (assert '(hasSymbol "ununtrium element*" "Uut"))
 (assert '(hasSymbol "flerovium element*" "Fl"))
 (assert '(hasSymbol "ununpentium element*" "Uup"))
 (assert '(hasSymbol "livermorium element*" "Lv"))
 (assert '(hasSymbol "ununseptium element*" "Uus"))
 (assert '(hasSymbol "ununoctium element*" "Uuo"))
