 (assert '(hasPhysicalQuantity "hydrogen element chemical species*" "relative atomic mass*" "1.008"))
 (assert '(hasPhysicalQuantity "helium element chemical species*" "relative atomic mass*" "4.0026"))
 (assert '(hasPhysicalQuantity "lithium element chemical species*" "relative atomic mass*" "6.94"))
 (assert '(hasPhysicalQuantity "beryllium element chemical species*" "relative atomic mass*" "9.0122"))
 (assert '(hasPhysicalQuantity "boron element chemical species*" "relative atomic mass*" "10.81"))
 (assert '(hasPhysicalQuantity "carbon element chemical species*" "relative atomic mass*" "12.011"))
 (assert '(hasPhysicalQuantity "nitrogen element chemical species*" "relative atomic mass*" "14.007"))
 (assert '(hasPhysicalQuantity "oxygen element chemical species*" "relative atomic mass*" "15.999"))
 (assert '(hasPhysicalQuantity "fluorine element chemical species*" "relative atomic mass*" "18.998"))
 (assert '(hasPhysicalQuantity "neon element chemical species*" "relative atomic mass*" "20.180"))
 (assert '(hasPhysicalQuantity "sodium element chemical species*" "relative atomic mass*" "22.990"))
 (assert '(hasPhysicalQuantity "magnesium element chemical species*" "relative atomic mass*" "24.305"))
 (assert '(hasPhysicalQuantity "aluminium element chemical species*" "relative atomic mass*" "26.982"))
 (assert '(hasPhysicalQuantity "silicon element chemical species*" "relative atomic mass*" "28.085"))
 (assert '(hasPhysicalQuantity "phosphorus element chemical species*" "relative atomic mass*" "30.974"))
 (assert '(hasPhysicalQuantity "sulfur element chemical species*" "relative atomic mass*" "32.06"))
 (assert '(hasPhysicalQuantity "chlorine element chemical species*" "relative atomic mass*" "35.45"))
 (assert '(hasPhysicalQuantity "argon element chemical species*" "relative atomic mass*" "39.948"))
 (assert '(hasPhysicalQuantity "potassium element chemical species*" "relative atomic mass*" "39.098"))
 (assert '(hasPhysicalQuantity "calcium element chemical species*" "relative atomic mass*" "40.078"))
 (assert '(hasPhysicalQuantity "scandium element chemical species*" "relative atomic mass*" "44.956"))
 (assert '(hasPhysicalQuantity "titanium element chemical species*" "relative atomic mass*" "47.867"))
 (assert '(hasPhysicalQuantity "vanadium element chemical species*" "relative atomic mass*" "50.942"))
 (assert '(hasPhysicalQuantity "chromium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "manganese  element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "iron element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "cobalt element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "nickel element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "copper element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "zinc element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "gallium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "germanium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "arsenic element chemical species*" "semi-metal class"))
 (assert '(hasPhysicalQuantity "selenium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "bromine element chemical species*" ""))
 (assert '(hasPhysicalQuantity "krypton element chemical species*" ""))
 (assert '(hasPhysicalQuantity "rubidium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "strontium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "yttrium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "zirconium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "niobium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "molybdenum element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "technetium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "ruthenium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "rhodium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "palladium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "silver element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "cadmium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "indium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "tin element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "antimony element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "tellurium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "iodine element chemical species*" ""))
 (assert '(hasPhysicalQuantity "xenon element chemical species*" ""))
 (assert '(hasPhysicalQuantity "caesium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "barium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "lanthanum element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "cerium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "praseodymium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "neodymium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "promethium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "samarium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "europium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "gadolinium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "terbium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "dysprosium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "holmium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "erbium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "thulium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "ytterbium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "lutetium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "hafnium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "tantalum element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "tungsten element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "rhenium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "osmium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "iridium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "platinum element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "gold element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "mercury element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "thallium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "lead element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "bismuth element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "polonium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "astatine element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "radon element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "francium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "radium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "actinium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "thorium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "protactinium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "uranium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "neptunium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "plutonium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "americium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "curium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "berkelium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "californium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "einsteinium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "fermium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "mendelevium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "nobelium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "lawrencium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "rutherfordium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "dubnium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "seaborgium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "bohrium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "hassium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "meitnerium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "darmstadtium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "roentgenium  element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "copernicium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "ununtrium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "flerovium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "ununpentium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "livermorium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "ununseptium element chemical species*" "relative atomic mass*" ""))
 (assert '(hasPhysicalQuantity "ununoctium element chemical species*" "relative atomic mass*" ""))
 
 (assert '(hasUnitaryPhysicalQuantity "hydrogen element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "helium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "lithium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "beryllium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "boron element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "carbon element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "nitrogen element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "oxygen element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "fluorine element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "neon element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "sodium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "magnesium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "aluminium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "silicon element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "phosphorus element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "sulfur element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "chlorine element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "argon element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "potassium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "calcium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "scandium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "titanium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "vanadium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "chromium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "manganese  element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "iron element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "cobalt element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "nickel element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "copper element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "zinc element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "gallium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "germanium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "arsenic element chemical species*" "semi-metal class"))
 (assert '(hasUnitaryPhysicalQuantity "selenium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "bromine element chemical species*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "krypton element chemical species*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "rubidium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "strontium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "yttrium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "zirconium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "niobium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "molybdenum element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "technetium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "ruthenium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "rhodium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "palladium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "silver element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "cadmium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "indium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "tin element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "antimony element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "tellurium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "iodine element chemical species*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "xenon element chemical species*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "caesium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "barium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "lanthanum element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "cerium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "praseodymium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "neodymium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "promethium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "samarium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "europium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "gadolinium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "terbium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "dysprosium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "holmium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "erbium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "thulium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "ytterbium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "lutetium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "hafnium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "tantalum element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "tungsten element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "rhenium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "osmium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "iridium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "platinum element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "gold element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "mercury element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "thallium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "lead element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "bismuth element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "polonium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "astatine element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "radon element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "francium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "radium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "actinium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "thorium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "protactinium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "uranium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "neptunium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "plutonium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "americium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "curium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "berkelium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "californium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "einsteinium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "fermium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "mendelevium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "nobelium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "lawrencium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "rutherfordium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "dubnium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "seaborgium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "bohrium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "hassium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "meitnerium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "darmstadtium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "roentgenium  element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "copernicium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "ununtrium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "flerovium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "ununpentium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "livermorium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "ununseptium element chemical species*" "boiling point*" "" "degree Celsius"))
 (assert '(hasUnitaryPhysicalQuantity "ununoctium element chemical species*" "boiling point*" "" "degree Celsius"))
 

(assert '(hasUnitaryPhysicalQuantity "hydrogen element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "helium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "lithium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "beryllium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "boron element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "carbon element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "nitrogen element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "oxygen element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "fluorine element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "neon element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "sodium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "magnesium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "aluminium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "silicon element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "phosphorus element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "sulfur element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "chlorine element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "argon element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "potassium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "calcium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "scandium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "titanium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "vanadium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "chromium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "manganese  element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "iron element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "cobalt element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "nickel element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "copper element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "zinc element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "gallium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "germanium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "arsenic element chemical species*" "semi-metal class"))
 (assert '(hasUnitaryPhysicalQuantity "selenium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "bromine element chemical species*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "krypton element chemical species*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "rubidium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "strontium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "yttrium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "zirconium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "niobium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "molybdenum element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "technetium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "ruthenium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "rhodium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "palladium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "silver element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "cadmium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "indium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "tin element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "antimony element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "tellurium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "iodine element chemical species*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "xenon element chemical species*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "caesium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "barium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "lanthanum element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "cerium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "praseodymium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "neodymium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "promethium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "samarium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "europium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "gadolinium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "terbium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "dysprosium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "holmium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "erbium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "thulium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "ytterbium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "lutetium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "hafnium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "tantalum element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "tungsten element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "rhenium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "osmium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "iridium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "platinum element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "gold element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "mercury element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "thallium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "lead element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "bismuth element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "polonium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "astatine element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "radon element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "francium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "radium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "actinium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "thorium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "protactinium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "uranium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "neptunium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "plutonium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "americium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "curium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "berkelium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "californium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "einsteinium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "fermium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "mendelevium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "nobelium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "lawrencium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "rutherfordium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "dubnium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "seaborgium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "bohrium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "hassium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "meitnerium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "darmstadtium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "roentgenium  element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "copernicium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "ununtrium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "flerovium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "ununpentium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "livermorium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "ununseptium element chemical species*" "density*" "" "gram per centimetre cubed"))
 (assert '(hasUnitaryPhysicalQuantity "ununoctium element chemical species*" "density*" "" "gram per centimetre cubed"))
