;;; periods
 (assert '(Ako "periodic table period 1 class*" "periodic table period class*"))
 (assert '(Ako "periodic table period 2 class*" "periodic table period class*"))
 (assert '(Ako "periodic table period 3 class*" "periodic table period class*"))
 (assert '(Ako "periodic table period 4 class*" "periodic table period class*"))
 (assert '(Ako "periodic table period 5 class*" "periodic table period class*"))
 (assert '(Ako "periodic table period 6 class*" "periodic table period class*"))
 (assert '(Ako "periodic table period 7 class*" "periodic table period class*"))
 ;;; period names
 (assert '(hasClassName "periodic table period 1 class*" "period 1"))
 (assert '(hasClassName "periodic table period 2 class*" "period 2"))
 (assert '(hasClassName "periodic table period 3 class*" "period 3"))
 (assert '(hasClassName "periodic table period 4 class*" "period 4"))
 (assert '(hasClassName "periodic table period 5 class*" "period 5"))
 (assert '(hasClassName "periodic table period 6 class*" "period 6"))
 (assert '(hasClassName "periodic table period 7 class*" "period 7"))
 (assert '(hasClassMemberName "periodic table period 1 class*" "period 1 element"))
 (assert '(hasClassMemberName "periodic table period 2 class*" "period 2 element"))
 (assert '(hasClassMemberName "periodic table period 3 class*" "period 3 element"))
 (assert '(hasClassMemberName "periodic table period 4 class*" "period 4 element"))
 (assert '(hasClassMemberName "periodic table period 5 class*" "period 5 element"))
 (assert '(hasClassMemberName "periodic table period 6 class*" "period 6 element"))
 (assert '(hasClassMemberName "periodic table period 7 class*" "period 7 element"))
 ;;; groups
 (assert '(Ako "periodic table group 1 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 2 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 3 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 4 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 5 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 6 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 7 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 8 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 9 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 10 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 11 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 12 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 13 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 14 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 15 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 16 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 17 class*" "periodic table group class*"))
 (assert '(Ako "periodic table group 18 class*" "periodic table group class*"))
 ;;; class names
 (assert '(hasClassName "periodic table group class*" (setof "periodic table group" "element group" "group")))
 (assert '(hasClassName "periodic table group 1 class*" (setof "group 1" "lithium family")))
 (assert '(hasClassName "periodic table group 2 class*" (setof "group 2" "beryllium family")))
 (assert '(hasClassName "periodic table group 3 class*" (setof "group 3" "scandium family")))
 (assert '(hasClassName "periodic table group 4 class*" (setof "group 4" "titanium family")))
 (assert '(hasClassName "periodic table group 5 class*" (setof "group 5" "vanadium family")))
 (assert '(hasClassName "periodic table group 6 class*" (setof "group 6" "chromium family")))
 (assert '(hasClassName "periodic table group 7 class*" (setof "group 7" "managanese family")))
 (assert '(hasClassName "periodic table group 8 class*" (setof "group 8" "iron group")))
 (assert '(hasClassName "periodic table group 9 class*" (setof "group 9" "cobalt family")))
 (assert '(hasClassName "periodic table group 10 class*" (setof "group 10" "nickel family")))
 (assert '(hasClassName "periodic table group 11 class*" (setof "group 11" "copper family")))
 (assert '(hasClassName "periodic table group 12 class*" (setof "group 12" "zinc family")))
 (assert '(hasClassName "periodic table group 13 class*" (setof "group 13" "boron family")))
 (assert '(hasClassName "periodic table group 14 class*" (setof "group 14" "carbon family")))
 (assert '(hasClassName "periodic table group 15 class*" (setof "group 15" "nitrogen family")))
 (assert '(hasClassName "periodic table group 16 class*" (setof "group 16" "oxygen family")))
 (assert '(hasClassName "periodic table group 17 class*" (setof "group 17" "fluorine group")))
 (assert '(hasClassName "periodic table group 18 class*" (setof "group 18" "helium family")))
 ;;; group membership
 (assert '(Isa "hydrogen element*" "periodic table group 1 class*"))
 (assert '(Isa "helium element*" "periodic table group 18 class*"))
 (assert '(Isa "lithium element*" "periodic table group 1 class*"))
 (assert '(Isa "beryllium element*" "periodic table group 2 class*"))
 (assert '(Isa "boron element*" "periodic table group 13 class*"))
 (assert '(Isa "carbon element*" "periodic table group 14 class*"))
 (assert '(Isa "nitrogen element*" "periodic table group 15 class*"))
 (assert '(Isa "oxygen element*" "periodic table group 16 class*"))
 (assert '(Isa "fluorine element*" "periodic table group 17 class*"))
 (assert '(Isa "neon element*" "periodic table group 18 class*"))
 (assert '(Isa "sodium element*" "periodic table group 1 class*"))
 (assert '(Isa "magnesium element*" "periodic table group 2 class*"))
 (assert '(Isa "aluminium element*" "periodic table group 13 class*"))
 (assert '(Isa "silicon element*" "periodic table group 14 class*"))
 (assert '(Isa "phosphorus element*" "periodic table group 15 class*"))
 (assert '(Isa "sulfur element*" "periodic table group 16 class*"))
 (assert '(Isa "chlorine element*" "periodic table group 17 class*"))
 (assert '(Isa "argon element*" "periodic table group 18 class*"))
 (assert '(Isa "potassium element*" "periodic table group 1 class*"))
 (assert '(Isa "calcium element*" "periodic table group 2 class*"))
 (assert '(Isa "scandium element*" "periodic table group 3 class*"))
 (assert '(Isa "titanium element*" "periodic table group 4 class*"))
 (assert '(Isa "vanadium element*" "periodic table group 5 class*"))
 (assert '(Isa "chromium element*" "periodic table group 6 class*"))
 (assert '(Isa "manganese  element*" "periodic table group 7 class*"))
 (assert '(Isa "iron element*" "periodic table group 8 class*"))
 (assert '(Isa "cobalt element*" "periodic table group 9 class*"))
 (assert '(Isa "nickel element*" "periodic table group 10 class*"))
 (assert '(Isa "copper element*" "periodic table group 11 class*"))
 (assert '(Isa "zinc element*" "periodic table group 12 class*"))
 (assert '(Isa "gallium element*" "periodic table group 13 class*"))
 (assert '(Isa "germanium element*" "periodic table group 14 class*"))
 (assert '(Isa "arsenic element*" "periodic table group 15 class*"))
 (assert '(Isa "selenium element*" "periodic table group 16 class*"))
 (assert '(Isa "bromine element*" "periodic table group 17 class*"))
 (assert '(Isa "krypton element*" "periodic table group 18 class*"))
 (assert '(Isa "rubidium element*" "periodic table group 1 class*"))
 (assert '(Isa "strontium element*" "periodic table group 2 class*"))
 (assert '(Isa "yttrium element*" "periodic table group 3 class*"))
 (assert '(Isa "zirconium element*" "periodic table group 4 class*"))
 (assert '(Isa "niobium element*" "periodic table group 5 class*"))
 (assert '(Isa "molybdenum element*" "periodic table group 6 class*"))
 (assert '(Isa "technetium element*" "periodic table group 7 class*"))
 (assert '(Isa "ruthenium element*" "periodic table group 8 class*"))
 (assert '(Isa "rhodium element*" "periodic table group 9 class*"))
 (assert '(Isa "palladium element*" "periodic table group 10 class*"))
 (assert '(Isa "silver element*" "periodic table group 11 class*"))
 (assert '(Isa "cadmium element*" "periodic table group 12 class*"))
 (assert '(Isa "indium element*" "periodic table group 13 class*"))
 (assert '(Isa "tin element*" "periodic table group 14 class*"))
 (assert '(Isa "antimony element*" "periodic table group 15 class*"))
 (assert '(Isa "tellurium element*" "periodic table group 16 class*"))
 (assert '(Isa "iodine element*" "periodic table group 17 class*"))
 (assert '(Isa "xenon element*" "periodic table group 18 class*"))
 (assert '(Isa "caesium element*" "periodic table group 1 class*"))
 (assert '(Isa "barium element*" "periodic table group 2 class*"))
 (assert '(Isa "lanthanum element*" "periodic table group 3 class*"))
 (assert '(Isa "cerium element*" "periodic table group 4 class*"))
 (assert '(Isa "praseodymium element*" "periodic table group 5 class*"))
 (assert '(Isa "neodymium element*" "periodic table group 6 class*"))
 (assert '(Isa "promethium element*" "periodic table group 7 class*"))
 (assert '(Isa "samarium element*" "periodic table group 8 class*"))
 (assert '(Isa "europium element*" "periodic table group 9 class*"))
 (assert '(Isa "gadolinium element*" "periodic table group 10 class*"))
 (assert '(Isa "terbium element*" "periodic table group 11 class*"))
 (assert '(Isa "dysprosium element*" "periodic table group 12 class*"))
 (assert '(Isa "holmium element*" "periodic table group 13 class*"))
 (assert '(Isa "erbium element*" "periodic table group 14 class*"))
 (assert '(Isa "thulium element*" "periodic table group 15 class*"))
 (assert '(Isa "ytterbium element*" "periodic table group 16 class*"))
 (assert '(Isa "lutetium element*" "periodic table group 3 class*"))
 (assert '(Isa "hafnium element*" "periodic table group 4 class*"))
 (assert '(Isa "tantalum element*" "periodic table group 5 class*"))
 (assert '(Isa "tungsten element*" "periodic table group 6 class*"))
 (assert '(Isa "rhenium element*" "periodic table group 7 class*"))
 (assert '(Isa "osmium element*" "periodic table group 8 class*"))
 (assert '(Isa "iridium element*" "periodic table group 9 class*"))
 (assert '(Isa "platinum element*" "periodic table group 10 class*"))
 (assert '(Isa "gold element*" "periodic table group 11 class*"))
 (assert '(Isa "mercury element*" "periodic table group 12 class*"))
 (assert '(Isa "thallium element*" "periodic table group 13 class*"))
 (assert '(Isa "lead element*" "periodic table group 14 class*"))
 (assert '(Isa "bismuth element*" "periodic table group 15 class*"))
 (assert '(Isa "polonium element*" "periodic table group 16 class*"))
 (assert '(Isa "astatine element*" "periodic table group 17 class*"))
 (assert '(Isa "radon element*" "periodic table group 18 class*"))
 (assert '(Isa "francium element*" "periodic table group 1 class*"))
 (assert '(Isa "radium element*" "periodic table group 2 class*"))
 (assert '(Isa "actinium element*" "periodic table group 3 class*"))
 (assert '(Isa "thorium element*" "periodic table group 4 class*"))
 (assert '(Isa "protactinium element*" "periodic table group 5 class*"))
 (assert '(Isa "uranium element*" "periodic table group 6 class*"))
 (assert '(Isa "neptunium element*" "periodic table group 7 class*"))
 (assert '(Isa "plutonium element*" "periodic table group 8 class*"))
 (assert '(Isa "americium element*" "periodic table group 9 class*"))
 (assert '(Isa "curium element*" "periodic table group 10 class*"))
 (assert '(Isa "berkelium element*" "periodic table group 11 class*"))
 (assert '(Isa "californium element*" "periodic table group 12 class*"))
 (assert '(Isa "einsteinium element*" "periodic table group 13 class*"))
 (assert '(Isa "fermium element*" "periodic table group 14 class*"))
 (assert '(Isa "mendelevium element*" "periodic table group 15 class*"))
 (assert '(Isa "nobelium element*" "periodic table group 16 class*"))
 (assert '(Isa "lawrencium element*" "periodic table group 3 class*"))
 (assert '(Isa "rutherfordium element*" "periodic table group 4 class*"))
 (assert '(Isa "dubnium element*" "periodic table group 5 class*"))
 (assert '(Isa "seaborgium element*" "periodic table group 6 class*"))
 (assert '(Isa "bohrium element*" "periodic table group 7 class*"))
 (assert '(Isa "hassium element*" "periodic table group 8 class*"))
 (assert '(Isa "meitnerium element*" "periodic table group 9 class*"))
 (assert '(Isa "darmstadtium element*" "periodic table group 10 class*"))
 (assert '(Isa "roentgenium  element*" "periodic table group 11 class*"))
 (assert '(Isa "copernicium element*" "periodic table group 12 class*"))
 (assert '(Isa "ununtrium element*" "periodic table group 13 class*"))
 (assert '(Isa "flerovium element*" "periodic table group 14 class*"))
 (assert '(Isa "ununpentium element*" "periodic table group 15 class*"))
 (assert '(Isa "livermorium element*" "periodic table group 16 class*"))
 (assert '(Isa "ununseptium element*" "periodic table group 17 class*"))
 (assert '(Isa "ununoctium element*" "periodic table group 18 class*"))
 ;;; period membership
 (assert '(Isa "hydrogen element*" "periodic table period 1 class*"))
 (assert '(Isa "helium element*" "periodic table period 1 class*"))
 (assert '(Isa "lithium element*" "periodic table period 2 class*"))
 (assert '(Isa "beryllium element*" "periodic table period 2 class*"))
 (assert '(Isa "boron element*" "periodic table period 2 class*"))
 (assert '(Isa "carbon element*" "periodic table period 2 class*"))
 (assert '(Isa "nitrogen element*" "periodic table period 2 class*"))
 (assert '(Isa "oxygen element*" "periodic table period 2 class*"))
 (assert '(Isa "fluorine element*" "periodic table period 2 class*"))
 (assert '(Isa "neon element*" "periodic table period 2 class*"))
 (assert '(Isa "sodium element*" "periodic table period 3 class*"))
 (assert '(Isa "magnesium element*" "periodic table period 3 class*"))
 (assert '(Isa "aluminium element*" "periodic table period 3 class*"))
 (assert '(Isa "silicon element*" "periodic table period 3 class*"))
 (assert '(Isa "phosphorus element*" "periodic table period 3 class*"))
 (assert '(Isa "sulfur element*" "periodic table period 3 class*"))
 (assert '(Isa "chlorine element*" "periodic table period 3 class*"))
 (assert '(Isa "argon element*" "periodic table period 3 class*"))
 (assert '(Isa "potassium element*" "periodic table period 4 class*"))
 (assert '(Isa "calcium element*" "periodic table period 4 class*"))
 (assert '(Isa "scandium element*" "periodic table period 4 class*"))
 (assert '(Isa "titanium element*" "periodic table period 4 class*"))
 (assert '(Isa "vanadium element*" "periodic table period 4 class*"))
 (assert '(Isa "chromium element*" "periodic table period 4 class*"))
 (assert '(Isa "manganese  element*" "periodic table period 4 class*"))
 (assert '(Isa "iron element*" "periodic table period 4 class*"))
 (assert '(Isa "cobalt element*" "periodic table period 4 class*"))
 (assert '(Isa "nickel element*" "periodic table period 4 class*"))
 (assert '(Isa "copper element*" "periodic table period 4 class*"))
 (assert '(Isa "zinc element*" "periodic table period 4 class*"))
 (assert '(Isa "gallium element*" "periodic table period 4 class*"))
 (assert '(Isa "germanium element*" "periodic table period 4 class*"))
 (assert '(Isa "arsenic element*" "periodic table period 4 class*"))
 (assert '(Isa "selenium element*" "periodic table period 4 class*"))
 (assert '(Isa "bromine element*" "periodic table period 4 class*"))
 (assert '(Isa "krypton element*" "periodic table period 4 class*"))
 (assert '(Isa "rubidium element*" "periodic table period 5 class*"))
 (assert '(Isa "strontium element*" "periodic table period 5 class*"))
 (assert '(Isa "yttrium element*" "periodic table period 5 class*"))
 (assert '(Isa "zirconium element*" "periodic table period 5 class*"))
 (assert '(Isa "niobium element*" "periodic table period 5 class*"))
 (assert '(Isa "molybdenum element*" "periodic table period 5 class*"))
 (assert '(Isa "technetium element*" "periodic table period 5 class*"))
 (assert '(Isa "ruthenium element*" "periodic table period 5 class*"))
 (assert '(Isa "rhodium element*" "periodic table period 5 class*"))
 (assert '(Isa "palladium element*" "periodic table period 5 class*"))
 (assert '(Isa "silver element*" "periodic table period 5 class*"))
 (assert '(Isa "cadmium element*" "periodic table period 5 class*"))
 (assert '(Isa "indium element*" "periodic table period 5 class*"))
 (assert '(Isa "tin element*" "periodic table period 5 class*"))
 (assert '(Isa "antimony element*" "periodic table period 5 class*"))
 (assert '(Isa "tellurium element*" "periodic table period 5 class*"))
 (assert '(Isa "iodine element*" "periodic table period 5 class*"))
 (assert '(Isa "xenon element*" "periodic table period 5 class*"))
 (assert '(Isa "caesium element*" "periodic table period 6 class*"))
 (assert '(Isa "barium element*" "periodic table period 6 class*"))
 (assert '(Isa "lanthanum element*" "periodic table period 6 class*"))
 (assert '(Isa "cerium element*" "periodic table period 6 class*"))
 (assert '(Isa "praseodymium element*" "periodic table period 6 class*"))
 (assert '(Isa "neodymium element*" "periodic table period 6 class*"))
 (assert '(Isa "promethium element*" "periodic table period 6 class*"))
 (assert '(Isa "samarium element*" "periodic table period 6 class*"))
 (assert '(Isa "europium element*" "periodic table period 6 class*"))
 (assert '(Isa "gadolinium element*" "periodic table period 6 class*"))
 (assert '(Isa "terbium element*" "periodic table period 6 class*"))
 (assert '(Isa "dysprosium element*" "periodic table period 6 class*"))
 (assert '(Isa "holmium element*" "periodic table period 6 class*"))
 (assert '(Isa "erbium element*" "periodic table period 6 class*"))
 (assert '(Isa "thulium element*" "periodic table period 6 class*"))
 (assert '(Isa "ytterbium element*" "periodic table period 6 class*"))
 (assert '(Isa "lutetium element*" "periodic table group 3 class*"))
 (assert '(Isa "hafnium element*" "periodic table group 4 class*"))
 (assert '(Isa "tantalum element*" "periodic table group 5 class*"))
 (assert '(Isa "tungsten element*" "periodic table group 6 class*"))
 (assert '(Isa "rhenium element*" "periodic table group 7 class*"))
 (assert '(Isa "osmium element*" "periodic table group 8 class*"))
 (assert '(Isa "iridium element*" "periodic table group 9 class*"))
 (assert '(Isa "platinum element*" "periodic table group 10 class*"))
 (assert '(Isa "gold element*" "periodic table group 11 class*"))
 (assert '(Isa "mercury element*" "periodic table group 12 class*"))
 (assert '(Isa "thallium element*" "periodic table group 13 class*"))
 (assert '(Isa "lead element*" "periodic table group 14 class*"))
 (assert '(Isa "bismuth element*" "periodic table group 15 class*"))
 (assert '(Isa "polonium element*" "periodic table group 16 class*"))
 (assert '(Isa "astatine element*" "periodic table group 17 class*"))
 (assert '(Isa "radon element*" "periodic table group 18 class*"))
 (assert '(Isa "francium element*" "periodic table period 6 class*"))
 (assert '(Isa "radium element*" "periodic table period 6 class*"))
 (assert '(Isa "actinium element*" "periodic table period 6 class*"))
 (assert '(Isa "thorium element*" "periodic table period 7 class*"))
 (assert '(Isa "protactinium element*" "periodic table period 7 class*"))
 (assert '(Isa "uranium element*" "periodic table period 7 class*"))
 (assert '(Isa "neptunium element*" "periodic table period 7 class*"))
 (assert '(Isa "plutonium element*" "periodic table period 7 class*"))
 (assert '(Isa "americium element*" "periodic table period 7 class*"))
 (assert '(Isa "curium element*" "periodic table period 7 class*"))
 (assert '(Isa "berkelium element*" "periodic table period 7 class*"))
 (assert '(Isa "californium element*" "periodic table period 7 class*"))
 (assert '(Isa "einsteinium element*" "periodic table period 7 class*"))
 (assert '(Isa "fermium element*" "periodic table period 7 class*"))
 (assert '(Isa "mendelevium element*" "periodic table period 7 class*"))
 (assert '(Isa "nobelium element*" "periodic table period 7 class*"))
 (assert '(Isa "lawrencium element*" "periodic table period 7 class*"))
 (assert '(Isa "rutherfordium element*" "periodic table period 7 class*"))
 (assert '(Isa "dubnium element*" "periodic table period 7 class*"))
 (assert '(Isa "seaborgium element*" "periodic table period 7 class*"))
 (assert '(Isa "bohrium element*" "periodic table period 7 class*"))
 (assert '(Isa "hassium element*" "periodic table period 7 class*"))
 (assert '(Isa "meitnerium element*" "periodic table period 7 class*"))
 (assert '(Isa "darmstadtium element*" "periodic table period 7 class*"))
 (assert '(Isa "roentgenium  element*" "periodic table period 7 class*"))
 (assert '(Isa "copernicium element*" "periodic table period 7 class*"))
 (assert '(Isa "ununtrium element*" "periodic table period 7 class*"))
 (assert '(Isa "flerovium element*" "periodic table period 7 class*"))
 (assert '(Isa "ununpentium element*" "periodic table period 7 class*"))
 (assert '(Isa "livermorium element*" "periodic table period 7 class*"))
 (assert '(Isa "ununseptium element*" "periodic table period 7 class*"))
 (assert '(Isa "ununoctium element*" "periodic table period 7 class*"))
