;;; Enthalpy of vaporization. Enthalpy of fusion

 (assert '(hasUnitaryPhysicalQuantity "hydrogen element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "helium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lithium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "beryllium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "boron element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "carbon element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "nitrogen element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "oxygen element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "fluorine element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "neon element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "sodium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "magnesium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "aluminium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "silicon element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "phosphorus element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "sulfur element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "chlorine element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "argon element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "potassium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "calcium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "scandium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "titanium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "vanadium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "chromium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "manganese  element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "iron element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "cobalt element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "nickel element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "copper element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "zinc element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "gallium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "germanium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "arsenic element*" "semi-metal class"))
 (assert '(hasUnitaryPhysicalQuantity "selenium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "bromine element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "krypton element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rubidium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "strontium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "yttrium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "zirconium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "niobium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "molybdenum element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "technetium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ruthenium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rhodium element*" "boiling point*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "palladium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "silver element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "cadmium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "indium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tin element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "antimony element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tellurium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "iodine element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "xenon element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "caesium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "barium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lanthanum element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "cerium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "praseodymium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "neodymium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "promethium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "samarium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "europium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "gadolinium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "terbium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "dysprosium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "holmium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "erbium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "thulium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ytterbium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lutetium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "hafnium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tantalum element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tungsten element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rhenium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "osmium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "iridium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "platinum element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "gold element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "mercury element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "thallium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lead element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "bismuth element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "polonium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "astatine element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "radon element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "francium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "radium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "actinium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "thorium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "protactinium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "uranium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "neptunium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "plutonium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "americium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "curium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "berkelium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "californium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "einsteinium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "fermium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "mendelevium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "nobelium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lawrencium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rutherfordium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "dubnium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "seaborgium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "bohrium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "hassium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "meitnerium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "darmstadtium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "roentgenium  element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "copernicium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununtrium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "flerovium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununpentium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "livermorium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununseptium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununoctium element*" "enthalpy of vaporization*" "" "kilojoules per mole*"))
 
 (assert '(hasUnitaryPhysicalQuantity "hydrogen element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "helium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lithium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "beryllium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "boron element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "carbon element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "nitrogen element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "oxygen element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "fluorine element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "neon element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "sodium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "magnesium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "aluminium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "silicon element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "phosphorus element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "sulfur element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "chlorine element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "argon element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "potassium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "calcium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "scandium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "titanium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "vanadium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "chromium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "manganese  element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "iron element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "cobalt element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "nickel element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "copper element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "zinc element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "gallium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "germanium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "arsenic element*" "semi-metal class"))
 (assert '(hasUnitaryPhysicalQuantity "selenium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "bromine element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "krypton element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rubidium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "strontium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "yttrium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "zirconium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "niobium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "molybdenum element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "technetium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ruthenium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rhodium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "palladium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "silver element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "cadmium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "indium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tin element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "antimony element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tellurium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "iodine element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "xenon element*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "caesium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "barium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lanthanum element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "cerium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "praseodymium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "neodymium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "promethium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "samarium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "europium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "gadolinium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "terbium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "dysprosium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "holmium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "erbium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "thulium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ytterbium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lutetium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "hafnium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tantalum element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "tungsten element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rhenium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "osmium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "iridium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "platinum element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "gold element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "mercury element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "thallium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lead element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "bismuth element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "polonium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "astatine element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "radon element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "francium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "radium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "actinium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "thorium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "protactinium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "uranium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "neptunium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "plutonium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "americium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "curium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "berkelium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "californium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "einsteinium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "fermium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "mendelevium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "nobelium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "lawrencium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "rutherfordium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "dubnium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "seaborgium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "bohrium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "hassium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "meitnerium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "darmstadtium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "roentgenium  element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "copernicium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununtrium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "flerovium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununpentium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "livermorium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununseptium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
 (assert '(hasUnitaryPhysicalQuantity "ununoctium element*" "enthalpy of fusion*" "" "kilojoules per mole*"))
