;;; physical property class
(Isa "melting point*" "physical property class*")
(Isa "boiling point*" "physical property class*")
(Isa "electrical conductivity*" "physical property class*")
(Isa "thermal conductivity*" "physical property class*")
(Isa "length*" "physical property class*")
(Isa "area*" "physical property class*")
(Isa "volume*" "physical property class*")
(Isa "brittleness*" "physical property class*")
(Isa "color*" "physical property class*")
(Isa "concentration*" "physical property class*")
(Isa "density*" "physical property class*")
(Isa "distribution*" "physical property class*")
(Isa "electric charge*" "physical property class*")
(Isa "hardness*" "physical property class*")
(Isa "location*" "physical property class*")
(Isa "malleability*" "physical property class*")
(Isa "mass*" "physical property class*")
(Isa "momentum*" "physical property class*")
(Isa "angular momentum*" "physical property class*")
(Isa "opacity*" "physical property class*")
(Isa "pressure*" "physical property class*")
(Isa "solubility*" "physical property class*")
(Isa "specific heat*" "physical property class*")
(Isa "refractive index*" "physical property class*")
(Isa "spin*" "physical property class*")
(Isa "strength*" "physical property class*")
(Isa "stiffness*" "physical property class*")
(Isa "temperature*" "physical property class*")
(Isa "velocity*" "physical property class*")
(Isa "viscosity*" "physical property class*")
