;;; A

(defineSlot AccountFor :type :Thing)
(defineSlot Act :type :Thing)
(defineSlot act :type :Act)
(defineSlot added-substance :type :ChemicalSubstance)
(defineSlot analogue :type :Thing)
(defineSlot analysandum :type :Thing)
(defineSlot analyseILO :type :Thing)
(defineSlot applyILO :type :Thing)
(defineSlot ApproachOfTo :type :Thing)
(defineSlot ArrivalAt :type :Thing)
(defineSlot Arrival :type :Thing)
(defineSlot arrival :type :Thing)
(defineSlot arriving-thing :type :Thing)
(defineSlot ascertainILO :type :Thing)
(defineSlot asExample :type :Thing)
(defineSlot asIn :type :Thing)
(defineSlot aspect :type :Aspect)
(defineSlot assumption-set :type :Thing)

;;; B

(defineSlot base :type :Thing)
(defineSlot BasedOn :type :Thing)
(defineSlot Basing :type :Thing)
(defineSlot beam-constituent :type :Thing)
(defineSlot BeingNecessary :type :Thing)
(defineSlot BuiltOn :type :Thing)

;;; C

(defineSlot calculateILO :type :Thing)
(defineSlot cardinal-item :type :Thing)
(defineSlot carryOutILO :type :Thing)
(defineSlot categorise :type :Thing)
(defineSlot categoriseILO :type :Thing)
(defineSlot categorisable-thing :type :Thing)
(defineSlot category :type :Category)
(defineSlot Causation :type :Thing)
(defineSlot cause :type :Thing)
(defineSlot change :type :Thing)
(defineSlot changeIn :type :Thing)
(defineSlot characterisable-thing :type :Thing)
(defineSlot chemical-change :type :ChemicalChange)
(defineSlot chemical-entity :type :ChemicalEntity)
(defineSlot chemical-equation :type :ChemicalEquation)
(defineSlot chemical-formula :type :ChemicalFormula)
(defineSlot chemical-property :type :ChemicalProperty)
(defineSlot chemical-reaction :type :ChemicalReaction)
(defineSlot chemical-referent :type :ChemicalReferent)
(defineSlot solution :type :Solution)
(defineSlot chemical-structure :type :ChemicalStructure)
(defineSlot chemical-substance :type :ChemicalSubstance)
(defineSlot chemical-system :type :ChemicalSystem)
(defineSlot chemical-test :type :ChemicalTest)
(defineSlot Circumstance :type :Thing)
(defineSlot Circumstancing :type :Thing)
(defineSlot circumstances :type :Thing)
(defineSlot circumstances-of-use :type :Thing)
(defineSlot class-name :type :Name)
(defineSlot class-quantity :type :Quantity)
(defineSlot class-with-aspect :type :Category)
(defineSlot class-with-behavior :type :Category)
(defineSlot class-with-physical-properties :type :Category)
(defineSlot class-with-properties :type :Category)
(defineSlot class-with-property :type :Category)
(defineSlot classifyILO :type :Thing)
(defineSlot clause :type :Thing)
(defineSlot column-in-periodic-table :type :PeriodicTableColumn)
(defineSlot Commands :type :Thing)
(defineSlot comparative-aspect :type :Comparative)
(defineSlot comparative-thing :type :Thing)
(defineSlot comparative-sense :type :Thing)
(defineSlot compareILO :type :Thing)
(defineSlot comparison-set :type :Thing)
(defineSlot complex-ion :type :ComplexIon)
(defineSlot constructedOn :type :Thing)
(defineSlot constructible-thing :type :Thing)
(defineSlot constructILO :type :ILO)
(defineSlot contacters :type :Thing :min 2)
(defineSlot containing :type :Thing)
(defineSlot ContainsElement :type :Thing)
(defineSlot content :type :Thing)
(defineSlot Control :type :Thing)
(defineSlot controlling-entity :type :Entity)
(defineSlot Controls :type :Thing)
(defineSlot creating :type :Thing)
(defineSlot creationOf :type :Thing)
(defineSlot criterion :type :Thing)


;;; D

(defineSlot dataOn :type :Thing)
(defineSlot deduceHowILO :type :Thing)
(defineSlot deducible-entity :type :Entity)
(defineSlot deduceILO :type :Thing)
(defineSlot definable-thing :type :DefinableThing)
(defineSlot dependent :type :Thing)
(defineSlot dependent-entity :type :Entity)
(defineSlot dependent-quantity :type :Quantity)
(defineSlot departing-thing :type :Thing)
(defineSlot Departure :type :Thing)
(defineSlot departure :type :Thing)
(defineSlot departureOfFrom :type :Thing)
(defineSlot deriveILO :type :Thing)
(defineSlot describable-thing :type :Thing)
(defineSlot determineILO :type :Thing)
(defineSlot Determines :type :Thing)
(defineSlot differees :type :Thing :min 2)
(defineSlot differentiateBetweenILO :Thing)
(defineSlot discussILO :type :Thing)
(defineSlot discussible-thing :type :Thing)
(defineSlot displaced-referent :type :ChemicalReferent)
(defineSlot distinguishable-things :type :Thing)
(defineSlot Do :type :Thing)
(defineSlot Domain :type :Thing)
(defineSlot domain :type :Thing)
(defineSlot domain-predicate :type :Thing)

;;; E

(defineSlot effect :type :Thing)
(defineSlot Effect :type :Thing)
(defineSlot effectOf :type :Thing)
(defineSlot effectOfObjectiveInfluence :type :Thing)
(defineSlot effectOfOn :type :Thing)
(defineSlot effectOfTo :type :Thing)
(defineSlot effectOfClassOn :type :Thing)
(defineSlot electrochemical-cell :type :ElectrochemicalCell)
(defineSlot electrode :type :Electrode)
(defineSlot electrode-potential :type :ElectrodePotential)
(defineSlot element :type :Element)
(defineSlot eliminate :type :ChemicalSubstance)
(defineSlot employILO :type :Thing)
(defineSlot electronic-configuration :type :Property)
(defineSlot entering-group :type :ChemicalReferent)
(defineSlot entity :type :Entity)
(defineSlot entity-with-base :type :Entity)
(defineSlot entity-with-circumstances :type :Entity)
(defineSlot entity-with-explanation :type :Entity)
(defineSlot essential-for :type :Thing)
(defineSlot essential-thing :type :Thing)
(defineSlot e-value :type :EValue)
(defineSlot eventuality :type :Thing)
(defineSlot example :type :Thing)
(defineSlot examples :type :Thing)
(defineSlot executeILO :type :Thing)
(defineSlot Explain :type :Thing)
(defineSlot explainWhyILO :type :Thing)
(defineSlot explainTermILO :type :Thing)
(defineSlot explainAndUseTermILO :type :Thing)

;;; F

(defineSlot figureOutILO :type :Thing)
(defineSlot final-category :type :Category)
(defineSlot final-property :type :Property)
(defineSlot final-system :type :System)
(defineSlot formationOf :type :Thing)
(defineSlot formula :type :ChemicalFormula)
(defineSlot formula-type :type :ChemicalFormulaType)

;;; G

(defineSlot generationOf :type :Thing)
(defineSlot generic-member-name :type :Name)
(defineSlot goal :type :Thing)

;;; H

(defineSlot half-reaction :type :HalfReaction)
(defineSlot HasAcceptableCommonName :type :Thing)
(defineSlot HasAtomName :type :Thing)
(defineSlot HasChemicalName :type :Thing)
(defineSlot HasElementName :type :Thing)
(defineSlot HasGeneralIupacname :type :Thing)
(defineSlot HasIupacName :type :Thing)
(defineSlot HasIupacNameSubstitutive :type :Thing)
(defineSlot HasIupacNameAdditive :type :Thing)
(defineSlot HasMoleculeName :type :Thing)
(defineSlot HasName :type :Thing)
(defineSlot HasOtherName :type :Thing)
(defineSlot HasPreferredIupacName :type :Thing)
(defineSlot HasRetainedIupacName :type :Thing)
(defineSlot HasSubstanceName :type :Thing)
(defineSlot HasSystematicName :type :Thing)
(defineSlot hypothetical-event :type :Thing)

;;; I

(defineSlot identifiable-thing :type :Thing)
(defineSlot identifyILO :type :Thing)
(defineSlot ilo :type :ILO)
(defineSlot impactOfOn :type :Thing)
(defineSlot impactOfClassOn :type :Thing)
(defineSlot inChemicalSystem :type :Thing)
(defineSlot inCircumstances :type :Thing)
(defineSlot Including :type :Thing)
(defineSlot including :type :Thing)
(defineSlot includingExample :type :Thing)
(defineSlot Inclusion :type :Thing)
(defineSlot inclusion-set :type :Entity)
(defineSlot independent-quantity :type :Quantity)
(defineSlot InDomain :type :Thing)
(defineSlot inDomain :type :Thing)
(defineSlot inferILO :type :Thing)
(defineSlot influence :Thing)
(defineSlot influenced :Thing)
(defineSlot influencing-class :type :Category)
(defineSlot influencing-entity :type :Entity)
(defineSlot influencing-thing :type :Thing)
(defineSlot influenceOfOn :type :Thing)
(defineSlot influenceOfClassOn :type :Thing)
(defineSlot information :type :Thing)
(defineSlot informationOn :type :Thing)
(defineSlot Incorporating :type :Thing)
(defineSlot instrument :type :Thing)
(defineSlot Integrating :type :Thing)
(defineSlot interactant-classes :type :Category)
(defineSlot IntentionallyAct :type :Thing)
(defineSlot Interacting-classes :type :Category :min 2)
(defineSlot ionisation-ordinal :type :Ordinal)
(defineSlot ionisation-energy-value :type :UnitedValue)
(defineSlot inRelationTo :type :Thing)
(defineSlot inSystem :type :Thing)
(defineSlot inTermsOf :type :Thing)
(defineSlot interpretable-thing :type :Thing)
(defineSlot involving-entity :type :Entity)
(defineSlot involvate :type :Entity)
(defineSlot ionic-referent :type :IonicChemicalReferent)
(defineSlot IsConsequenceOf :type :Thing)
(defineSlot IsEffectOf :type :Thing)
(defineSlot IsEffectOfObjectiveInfluence :Thing) 
(defineSlot IsEssentialTo  :type :Thing)
(defineSlot IsResultOf :type :Thing)
(defineSlot IsMeansFor :type :Thing)
(defineSlot isMethodFor :type :Thing)
(defineSlot IsNecessaryFor :type :Thing)
(defineSlot IsRequiredFor :type :Thing)
(defineSlot isomer :type :Isomer)
(defineSlot isomer-type :type :IsomerType)
(defineSlot isotope :type :Thing)
(defineSlot IsCompoundOf :Thing)

;;; J

;;; K

;;; L

(defineSlot leaving-group :type :ChemicalReferent)
(defineSlot ligand :type :ChemicalReferent)
(defineSlot locality-of-distribution :type :Thing)

;;; M

(defineSlot magnitude :type :Number)
(defineSlot manner :type :Manner)
(defineSlot manufacturand :type :Thing)
(defineSlot matchILO :type :Thing)
(defineSlot Means :type :Thing)
(defineSlot means :type :Thing)
(defineSlot measurable-thing :type :Thing)
(defineSlot mer :type :ChemicalReferent)
(defineSlot metal-ion :type :MetalIon)
(defineSlot method :type :Thing)
(defineSlot modification :type :Thing :min 0)
(defineSlot modAsAppliedTo :type :Thing)
(defineSlot modInDomain :type :Thing)
(defineSlot modInTermsOf :type :Thing)
(defineSlot modInRelationTo :type :Thing)
(defineSlot modWithReferenceTo :type :Thing)
(defineSlot modWithRegardsTo :type :Thing)
(defineSlot modWithParticularReferenceTo :type :Thing)
(defineSlot MolecularConstitution :type :Thing)
(defineSlot molecular-structure :type :MolecularStructure)

;;; N

(defineSlot nameable-class :type :Category)
(defineSlot nameable-thing :type :NameableThing)
(defineSlot non-physical-property :type :NonPhysicalProperty)
(defineSlot number-of-atoms :type :WholeNumber)

;;; O

(defineSlot objectiveInfluence :type :Thing)
(defineSlot objective-influence :type :Thing)
(defineSlot objectiveInfluenceOfClass :type :Thing)
(defineSlot object-of-action :type :Thing)
(defineSlot object-of-calculation :type :Thing)
(defineSlot object-of-influence :type :Thing)
(defineSlot objectiveInfluenceToBringAbout :type :Thing)
(defineSlot operateILO :type :Thing)
(defineSlot oxidant :type :ChemicalReferent)

;;; P

(defineSlot Perform :type :Thing)
(defineSlot performCalculationsILO :type :Thing)
(defineSlot phenomena :type :Thing :min 2)
(defineSlot physical-property :type :PhysicalProperty)
(defineSlot physical-state :type :PhysicalState)
(defineSlot change-of-state :type :ChangeOfState)
(defineSlot physical-process :type :PhysicalProcess)
(defineSlot polymer :type :PolymerSubstance)
(defineSlot position-in-periodic-table :type :PeriodicTablePosition)
(defineSlot powerOfOver :type :Thing)
(defineSlot powerOfClassOver :type :Thing)
(defineSlot present-thing :type :Thing)
(defineSlot problem :type :Thing)
(defineSlot process :type :Process)
(defineSlot processed-thing :type :Thing)
(defineSlot productionOf :type :Thing)
(defineSlot product :type :ChemicalSubstance)
(defineSlot products :type :ChemicalSubstance)
(defineSlot property :type :Property)
(defineSlot proposeILO :type :Thing)
(defineSlot proposition :type :Proposition)
(defineSlot pure-chemical-substance-name :type :Name)
(defineSlot purpose :type :Act)
(defineSlot puzzleOutILO :type :Thing)

;;; Q

(defineSlot phenomenon :type :Thing)
(defineSlot qualification :type :Thing)
(defineSlot quantity :type :Quantity)

;;; R

(defineSlot reactant :type :ChemicalSubstance)
(defineSlot reactants :type :ChemicalSubstance)
(defineSlot reactant-class :type :ChemicalSubstanceClass)
(defineSlot reactant-class-2 :type :ChemicalSubstanceClass)
(defineSlot reactive-entity :type :Thing)
(defineSlot reactive-class :type :ChemicalSubstanceClass)
(defineSlot reactive-class-1 :type :ChemicalSubstanceClass)
(defineSlot reactive-class-2 :type :ChemicalSubstanceClass)
(defineSlot reaction-condition :type :ReactionCondition)
(defineSlot reaction-type :type :ReactionType)
(defineSlot reagent :type :ChemicalReagent)
(defineSlot recognizable-thing :type :Thing)
(defineSlot recountILO :type :Thing)
(defineSlot redox-reaction :type :RedoxReaction)
(defineSlot redox-system :type :RedoxSystem)
(defineSlot reductant :type :ChemicalReferent)
(defineSlot relate-source :type :Thing)
(defineSlot reactive-entities :type :ChemicalSpecies :min 2)
(defineSlot Regulates :type :Thing)
(defineSlot relate-sink :type :Thing)
(defineSlot RelateToILO :type :Thing)
(defineSlot removal-source :type :Thing)
(defineSlot removand :type :Thing)
(defineSlot renewed-thing :type :Thing)
(defineSlot reportILO :type :Thing)
(defineSlot requirement :type :Thing)
(defineSlot resource :type :Thing)
(defineSlot result-of :type :Thing)
(defineSlot result-of-calculation :type :Thing)
(defineSlot ResultsIn :type :Thing)
(defineSlot role :type :Role)
(defineSlot row-in-periodic-table :type :PeriodicTableRow)

;;; S

(defineSlot separable-things :type :Thing)
(defineSlot sequence :type :Thing)
(defineSlot shape :type :Thing)
(defineSlot showAwarenessOfILO :Thing)
(defineSlot sign :type :Thing)
(defineSlot shape-property :type :Thing)
(defineSlot similar-things :type :Thing :min 2)
(defineSlot Smaller :type :Thing)
(defineSlot stabilised-thing :type :Thing)
(defineSlot stabilisation-agency :type :Thing)
(defineSlot standard-cell-potential :type :StandardCellPotential)
(defineSlot statable-thing :type :Thing)
(defineSlot stateILO :type :Thing)
(defineSlot symbol :type :Thing)
(defineSlot symboled-entity :type :Thing)
(defineSlot derived-property :type :DerivedProperty)
(defineSlot substance :type :ChemicalSubstance)
(defineSlot substance-class :type :ChemicalSubstanceClass)
(defineSlot substitution-reaction :type :SubstitutionReaction)
(defineSlot substrate :type :ChemicalSubstance)
(defineSlot substrate-referent :type :ChemicalReferent)
(defineSlot substrate-substance :type :ChemicalSubstance)
(defineSlot substrate-class :type :ChemicalSubstanceClass)
(defineSlot symbolic-property-element :type :Thing)
(defineSlot symbolic-property-class :type :Category)
(defineSlot system :type :System)

(defineSlot subclass :type Category :negadjust reduce
            :path (compose ! subclass (kstar (compose superclass- ! subclass)))
            :docstring "Subcategories of some category/ies.")

(defineSlot SuggestILO :type :Thing)

(defineSlot superclass :type Category :negadjust reduce
            :path (compose ! superclass (kstar (compose subclass- ! superclass)))
            :docstring "Supercategories of some category/ies.")
(defineSlot SurmiseILO :type :Thing)

;;; T

(defineSlot tested-for-class :type :Category)
(defineSlot thing :type :Thing)
(defineSlot thing-arrived-at :type :Thing)
(defineSlot thing-created :type :Thing)
(defineSlot thing-departed-from :type :Thing)
(defineSlot thing-departing :type :Thing)
(defineSlot thing-given :type :Thing)
(defineSlot thing-in-presence :type :Thing)
(defineSlot thing-with-aspect :type :Thing)
(defineSlot thing-with-sequence :type :Thing)
(defineSlot thing-name :type :Name)
(defineSlot thing-to-be-determined :type :Thing)
(defineSlot thing-with-assumptions :type :Thing)
(defineSlot thing-with-behavior :type :Thing)
(defineSlot thing-with-cardinality :type :Thing)
(defineSlot thing-with-data :type :Thing)
(defineSlot thing-with-change :type :Thing)
(defineSlot thing-with-charge :type :Thing)
(defineSlot thing-with-conditions :type :Thing)
(defineSlot thing-with-direction :type :Thing)
(defineSlot thing-with-distribution :type :Thing)
(defineSlot thing-with-presence :type :Thing)
(defineSlot thing-with-property :type :Thing)
(defineSlot thing-with-quantity :type :Thing)
(defineSlot thing-with-role :type :Thing)
(defineSlot thing-with-shape :type :Thing)
(defineSlot thing-with-type :type :Thing)
(defineSlot things-with-property :type :Thing :min 2)
(defineSlot things-with-trending-property :type :Thing :min 2)
(defineSlot topic :type :Thing)
(defineSlot toxic-thing :type :ToxicThing)
(defineSlot trending-property :type :Thing)
(defineSlot type-of-action :type :Thing)
(defineSlot type-of-alteration :type :Thing)

;;; U

;;; V

(defineSlot value :type :Number)

;;; W

(defineSlot withExample :type :Thing)
(defineSlot withParticularReferenceTo :type :Thing)
(defineSlot withReferenceTo :type :Thing)
(defineSlot withRegardsTo :type :Thing)
(defineSlot workOutILO :type :Thing)
(defineSlot writable :type :Thing)
(defineSlot writeDownILO :type :Thing)
(defineSlot writeILO :type :Thing)

;;; X

;;; Y

;;; Z











