;;; ester chemical substances
(assert '(Isa "methyl methanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "methyl ethanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "methyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "methyl butanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "methyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "ethyl methanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "ethyl ethanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "ethyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "ethyl butanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "ethyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "propyl methanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "propyl ethanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "propyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "propyl butanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "propyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "butyl methanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "butyl ethanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "butyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "butyl butanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "butyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "pentyl methanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "pentyl ethanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "pentyl propanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "pentyl butanoate pure chemical substance*" "ester substance class*"))
(assert '(Isa "pentyl propanoate pure chemical substance*" "ester substance class*"))
;;; ester molecules
(assert '(Isa "methyl methanoate molecular entity*" "ester molecular entity class"))
(assert '(Isa "methyl ethanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "methyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "methyl butanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "methyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "ethyl methanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "ethyl ethanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "ethyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "ethyl butanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "ethyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "propyl methanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "propyl ethanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "propyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "propyl butanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "propyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "butyl methanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "butyl ethanoate molecular entity*" "ester molecular entity class*"))
 (assert '(Isa "butyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "butyl butanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "butyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "pentyl methanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "pentyl ethanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "pentyl propanoate molecular entity*" "ester molecular entity class*"))
(assert '(Isa "pentyl butanoate molecular entity" "ester molecular entity class*"))
(assert '(Isa "pentyl propanoate molecular entity*" "ester molecular entity class*"))
;;; ester substance names
(assert '(hasSystematicName "methyl methanoate pure chemical substance*" "methyl methanoate"))
(assert '(hasSystematicName "methyl ethanoate pure chemical substance*" "methyl ethanoate"))
(assert '(hasIupacName "methyl ethanoate pure chemical substance*" "methyl acetate"))
(assert '(hasSystematicName "methyl propanoate pure chemical substance*" "methyl propanoate"))
(assert '(hasSystematicName "methyl butanoate pure chemical substance*" "methyl butanoate"))
(assert '(hasSystematicName "methyl propanoate pure chemical substance*" "methyl propanoate"))
(assert '(hasSystematicName "ethyl methanoate pure chemical substance*" "ethyl methanoate"))
(assert '(hasSystematicName "ethyl ethanoate pure chemical substance*" "ethyl ethanoate"))
(assert '(hasIupacName "ethyl ethanoate pure chemical substance*" "ethyl acetate"))
(assert '(hasSystematicName "ethyl propanoate pure chemical substance*" "ethyl propanoate"))
(assert '(hasSystematicName "ethyl butanoate pure chemical substance*" "ethyl butanoate"))
(assert '(hasSystematicName "ethyl propanoate pure chemical substance*" "ethyl propanoate"))
(assert '(hasSystematicName "propyl methanoate pure chemical substance*" "propyl methanoate"))
(assert '(hasSystematicName "propyl ethanoate pure chemical substance*" "propyl ethanoate"))
(assert '(hasIupacName "propyl ethanoate pure chemical substance*" "propyl acetate"))
(assert '(hasSystematicName "propyl propanoate pure chemical substance*" "propyl propanoate"))
(assert '(hasSystematicName "propyl butanoate pure chemical substance*" "propyl butanoate"))
(assert '(hasSystematicName "propyl propanoate pure chemical substance*" "propyl propanoate"))
(assert '(hasSystematicName "butyl methanoate pure chemical substance*" "butyl methanoate"))
(assert '(hasSystematicName "butyl ethanoate pure chemical substance*" "butyl ethanoate"))
(assert '(hasIupacName "butyl ethanoate pure chemical substance*" "butyl acetate"))
(assert '(hasSystematicName "butyl propanoate pure chemical substance*" "butyl propanoate"))
(assert '(hasSystematicName "butyl butanoate pure chemical substance*" "butyl butanoate"))
(assert '(hasSystematicName "butyl propanoate pure chemical substance*" "butyl propanoate"))
(assert '(hasSystematicName "pentyl methanoate pure chemical substance*" "pentyl methanoate"))
(assert '(hasSystematicName "pentyl ethanoate pure chemical substance*" "pentyl ethanoate"))
(assert '(hasIupacName "pentyl ethanoate pure chemical substance*" "pentyl acetate"))
(assert '(hasSystematicName "pentyl propanoate pure chemical substance*" "pentyl propanoate"))
(assert '(hasSystematicName "pentyl butanoate pure chemical substance*" "pentyl butanoate"))
(assert '(hasSystematicName "pentyl propanoate pure chemical substance*" "pentyl propanoate"))
(assert '(hasSystematicName "methyl methanoate molecular entity*" "methyl methanoate"))
(assert '(hasSystematicName "methyl ethanoate molecular entity*" "methyl ethanoate"))
(assert '(hasIupacName "methyl ethanoate molecular entity*" "methyl acetate"))
(assert '(hasSystematicName "methyl propanoate molecular entity*" "methyl propanoate"))
(assert '(hasSystematicName "methyl butanoate molecular entity*" "methyl butanoate"))
(assert '(hasSystematicName "methyl propanoate molecular entity*" "methyl propanoate"))
(assert '(hasSystematicName "ethyl methanoate molecular entity*" "ethyl methanoate"))
(assert '(hasSystematicName "ethyl ethanoate molecular entity*" "ethyl ethanoate"))
(assert '(hasIupacName "ethyl ethanoate molecular entity*" "ethyl acetate"))
(assert '(hasSystematicName "ethyl propanoate molecular entity*" "ethyl propanoate"))
(assert '(hasSystematicName "ethyl butanoate molecular entity*" "ethyl butanoate"))
(assert '(hasSystematicName "ethyl propanoate molecular entity*" "ethyl propanoate"))
(assert '(hasSystematicName "propyl methanoate molecular entity*" "propyl methanoate"))
(assert '(hasSystematicName "propyl ethanoate molecular entity*" "propyl ethanoate"))
(assert '(hasIupacName "propyl ethanoate molecular entity*" "propyl acetate"))
(assert '(hasSystematicName "propyl propanoate molecular entity*" "propyl propanoate"))
(assert '(hasSystematicName "propyl butanoate molecular entity*" "propyl butanoate"))
(assert '(hasSystematicName "propyl propanoate molecular entity*" "propyl propanoate"))
(assert '(hasSystematicName "butyl methanoate molecular entity*" "butyl methanoate"))
(assert '(hasSystematicName "butyl ethanoate molecular entity*" "butyl ethanoate"))
(assert '(hasIupacName "butyl ethanoate molecular entity*" "butyl acetate"))
(assert '(hasSystematicName "butyl propanoate molecular entity*" "butyl propanoate"))
(assert '(hasSystematicName "butyl butanoate molecular entity*" "butyl butanoate"))
(assert '(hasSystematicName "butyl propanoate molecular entity*" "butyl propanoate"))
(assert '(hasSystematicName "pentyl methanoate molecular entity*" "pentyl methanoate"))
(assert '(hasSystematicName "pentyl ethanoate molecular entity*" "pentyl ethanoate"))
(assert '(hasIupacName "pentyl ethanoate molecular entity*" "pentyl acetate"))
(assert '(hasSystematicName "pentyl propanoate molecular entity*" "pentyl propanoate"))
(assert '(hasSystematicName "pentyl butanoate molecular entity" "pentyl butanoate"))
(assert '(hasSystematicName "pentyl propanoate molecular entity*" "pentyl propanoate"))
