;;; chemical referent class hierarchies
(assert '(Ako "organic chemical referent class*" "chemical referent class*"))
(assert '(Ako "hydrocarbon chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "alkane chemical referent class*" "hydrocarbon chemical referent class*"))
(assert '(Ako "alkene chemical referent class*" "hydrocarbon chemical referent class*"))
(assert '(Ako "alkyne chemical referent class*" "hydrocarbon chemical referent class*"))
(assert '(Ako "alkanol chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "primary alkanol chemical referent class*" "alkanol chemical referent class*"))
(assert '(Ako "secondary alkanol chemical referent class*" "alkanol chemical referent class*"))
(assert '(Ako "tertiary alkanol chemical referent class*" "alkanol chemical referent class*"))
(assert '(Ako "aldehyde chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "ketone chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "alkanoic acid chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "ester chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "amine chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "primary amine chemical referent class*" "amine chemical referent class*"))
(assert '(Ako "secondary amine chemical referent class*" "amine chemical referent class*"))
(assert '(Ako "tertiary amine chemical referent class*" "amine chemical referent class*"))
(assert '(Ako "halogenoalkane chemical referent class*" "organic chemical referent class*"))
(assert '(Ako "primary halogenoalkane chemical referent class*" "halogenoalkane chemical referent class*"))
(assert '(Ako "secondary halogenoalkane chemical referent class*" "halogenoalkane chemical referent class*"))
(assert '(Ako "tertiary halogenoalkane chemical referent class*" "halogenoalkane chemical referent class*"))
(assert '(Ako "ether chemical referent class*" "organic chemical referent class*"))
;;; pure chemical substance class hierarchies
(assert '(Ako "chemical substance class*" "chemical referent class*"))
(assert '(Ako "pure chemical substance class*" "chemical substance class*"))
(assert '(Ako "chemical species class*" "chemical referent class*"))
(assert '(Ako "chemical species class*" "pure chemical substance class*"))
(assert '(Ako "element class*" "chemical species class*"))
(assert '(Ako "organic pure chemical substance class*" "pure chemical substance class*"))
(assert '(Ako "hydrocarbon pure chemical substance class*" "organic pure chemical substance class*"))
(assert '(Ako "alkane substance class*" "hydrocarbon chemical substance class*"))
(assert '(Ako "alkene substance class*" "hydrocarbon chemical substance class*"))
(assert '(Ako "alkyne substance class*" "hydrocarbon chemical substance class*"))
(assert '(Ako "alkanol substance class*" "pure chemical substance class*"))
(assert '(Ako "primary alkanol substance class*" "alkanol substance class*"))
(assert '(Ako "secondary alkanol substance class*" "alkanol substance class*"))
(assert '(Ako "tertiary alkanol substance class*" "alkanol substance class*"))
(assert '(Ako "amine substance class*" "organic pure chemical substance class*"))
(assert '(Ako "primary amine substance class*" "amine substance class**"))
(assert '(Ako "secondary amine substance class*" "amine substance class**"))
(assert '(Ako "tertiary amine substance class*" "amine substance class**"))
(assert '(Ako "aldehyde substance class*" "organic pure chemical substance class*"))
(assert '(Ako "ketone substance class*" "organic pure chemical substance class*"))
(assert '(Ako "carboxylic acid substance class*" "organic pure chemical substance class*"))
(assert '(Ako "ester substance class*" "organic pure chemical substance class*"))
(assert '(Ako "halogenoalkane substance class*" "organic pure chemical substance class*"))
(assert '(Ako "fluoroalkane substance class*" "halogenoalkane substance class*"))
(assert '(Ako "chloroalkane substance class*" "halogenoalkane substance class*"))
(assert '(Ako "bromoalkane substance class*" "halogenoalkane substance class*"))
(assert '(Ako "iodoalkane substance class*" "halogenoalkane substance class*"))
;;; molecular entity class hierarchies
(assert '(Ako "chemical entity class*" "chemical referent class*"))
(assert '(Ako "molecular chemical entity class*" "chemical entity class*"))
(assert '(Ako "organic molecular chemical entity class*" "molecular chemical entity class*"))
(assert '(Ako "hydrocarbon molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "alkane molecular entity class*" "hydrocarbon molecular entity class*"))
(assert '(Ako "alkene molecular entity class*" "hydrocarbon molecular entity class*"))
(assert '(Ako "alkyne molecular entity class*" "hydrocarbon molecular entity class*"))
(assert '(Ako "alkanol molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "primary alkanol molecular entity class*" "alkanol molecular entity class*"))
(assert '(Ako "secondary alkanol chemical entity class*" "alkanol molecular entity class*"))
(assert '(Ako "tertiary alkanol chemical entity class*" "alkanol molecular entity class*"))
(assert '(Ako "aldehyde molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "ketone molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "carboxylic acid molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "amine molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "primary amine molecular entity class*" "amine molecular entity class*"))
(assert '(Ako "secondary amine molecular entity class*" "amine molecular entity class*"))
(assert '(Ako "tertiary amine molecular entity class*" "amine molecular entity class*"))
(assert '(Ako "ester molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "halogenoalkane molecular entity class*" "organic molecular chemical entity class*"))
(assert '(Ako "fluoroalkane molecular entity class*" "halogenoalkane molecular entity class*"))
(assert '(Ako "chloroalkane molecular entity class*" "halogenoalkane molecular entity class*"))
(assert '(Ako "bromoalkane molecular entity class*" "halogenoalkane molecular entity class*"))
(assert '(Ako "iodoalkane molecular entity class*" "halogenoalkane molecular entity class*"))
(assert '(Ako "primary halogenalkane chemical referent class*" "chemical referent class*"))
(assert '(Ako "secondary halogenalkane chemical referent class*" "chemical referent class*"))
(assert '(Ako "tertiary halogenalkane chemical referent class*" "chemical referent class*"))
;;; class names 
;; referents
(assert '(hasClassName "chemical referent class*" "chemical object"))
(assert '(hasClassName "organic chemical referent class*" "organic"))
(assert '(hasClassName "hydrocarbon chemical referent class*" "hydrocarbon"))
(assert '(hasClassName "alkane chemical referent class*" "alkane"))
(assert '(hasClassName "alkene chemical referent class*" "alkene"))
(assert '(hasClassName "alkyne chemical referent class*" "alkyne"))
(assert '(hasClassName "alkanol chemical referent class*" (setof alkanol alcohol)))
(assert '(hasClassName "primary alkanol chemical referent class*" (setof "primary alcohol" "primary alkanol")))
(assert '(hasClassName "secondary alkanol chemical referent class*" (setof "secondary alkanol" "secondary alcohol")))
(assert '(hasClassName "tertiary alkanol chemical referent class*" (setof "tertiary alkanol" "tertiary alcohol")))
(assert '(hasClassName "aldehyde chemical referent class*" "aldehyde"))
(assert '(hasClassName "ketone chemical referent class*" "ketone"))
(assert '(hasClassName "alkanoic acid chemical referent class*" (setof "carboxylic acid" "alkanoic acid")))
(assert '(hasClassName "ester chemical referent class*" "ester"))
(assert '(hasClassName "amine chemical referent class*" "amine"))
(assert '(hasClassName "primary amine chemical referent class*" "primary amine"))
(assert '(hasClassName "secondary amine chemical referent class*" "secondary amine"))
(assert '(hasClassName "tertiary amine chemical referent class*" "tertiary amine"))
(assert '(hasClassName "halogenoalkane chemical referent class*" (setof "halogenoalkane" "haloalkane" "alkyl halide")))
(assert '(hasClassName "primary halogenoalkane chemical referent class*" (setof "primary halogenoalkane" "primary haloalkane" "primary alkyl halide")))
(assert '(hasClassName "secondary halogenoalkane chemical referent class*" (setof "secondary halogenoalkane" "secondary haloalkane" "secondary alkyl halide")))
(assert '(hasClassName "tertiary halogenoalkane chemical referent class*" (setof "tertiary halogenoalkane" "tertiary haloalkane" "tertiary alkyl halide")))
(assert '(hasClassName "ether chemical referent class*" "ether"))
 ;; susbtances and entities
(assert '(hasClassName "chemical substance class*" "chemical substance"))
(assert '(hasClassName "pure chemical substance class*" "pure chemical substance"))
(assert '(hasClassName "organic pure chemical substance class*" "organic pure chemical substance"))
(assert '(hasClassName "hydrocarbon chemical substance class*" "hydrocarbon"))
(assert '(hasClassName "chemical entity class*" "chemical entity"))
(assert '(hasClassName "molecular chemical entity class*" "molecular entity"))
(assert '(hasClassName "organic molecular chemical entity class*" "organic molecule"))
(assert '(hasClassName "hydrocarbon molecular entity class*" "hydrocarbon"))
(assert '(hasClassName "alkane substance class*" "alkane"))
(assert '(hasClassName "alkane molecular entity class*" "alkane"))
(assert '(hasClassName "alkene substance class*" "alkene"))
(assert '(hasClassName "alkene molecular entity class*" "alkene"))
(assert '(hasClassName "alkyne substance class*" alkyne))
(assert '(hasClassName "alkyne molecular entity class*" alkyne))
(assert '(hasClassName "ester substance class*" ester))
(assert '(hasClassName "ester molecular entity class*" ester))
(assert '(hasClassName "aldehyde substance class*" aldehyde))
(assert '(hasClassName "aldehyde molecular entity class*" aldehyde))
(assert '(hasClassName "ketone substance class*" ketone))
(assert '(hasClassName "ketone molecular entity class*" ketone))
(assert '(hasClassName "carboxylic acid substance class*" "carboxylic acid"))
(assert '(hasClassName "carboxylic acid molecular entity class*" "carboxylic acid"))
(assert '(hasClassName "alkanol substance class*" alkanol))
(assert '(hasClassName "alkanol molecular entity class*" alkanol))
(assert '(hasClassName "alkanol substance class*" alcohol))
(assert '(hasClassName "alkanol molecular entity class*" alcohol))
(assert '(hasClassName "primary alkanol substance class*" "primary alcohol"))
(assert '(hasClassName "secondary alkanol substance class*" "secondary alcohol"))
(assert '(hasClassName "tertiary alkanol substance class*" "tertiary alcohol"))
(assert '(hasClassName "amine substance class*" amine))
(assert '(hasClassName "amine molecular entity class*" amine))
(assert '(hasClassName "primary amine substance class*" "primary amine"))
(assert '(hasClassName "primary amine molecular entity class*" "primary amine"))
(assert '(hasClassName "secondary amine substance class*" "secondary amine"))
(assert '(hasClassName "secondary amine molecular entity class*" "secondary amine"))
(assert '(hasClassName "tertiary amine substance class*" "tertiary amine"))
(assert '(hasClassName "tertiary amine molecular entity class*" "tertiary amine"))
(assert '(hasClassName "halogenoalkane substance class*" (setof halogenoalkane haloalkane "alkyl halide")))
(assert '(hasClassName "fluoroalkane substance class*" "fluoroalkane"))
(assert '(hasClassName "chloroalkane substance class*" "chloroalkane"))
(assert '(hasClassName "bromoalkane substance class*" "bromoalkane"))
(assert '(hasClassName "iodoalkane substance class*" "iodoalkane"))
(assert '(hasClassName "halogenoalkane molecular entity class*" (setof halogenoalkane haloalkane "alkyl halide")))
(assert '(hasClassName "fluoroalkane molecular entity class*" "fluoroalkane"))
(assert '(hasClassName "chloroalkane molecular entity class*" "chloroalkane"))
(assert '(hasClassName "bromoalkane molecular entity class*" "bromoalkane"))
(assert '(hasClassName "iodoalkane molecular entity class*" "iodoalkane"))
(assert '(hasClassName "primary halogenalkane chemical referent class*" (setof "primary halogenoalkane" "primary haloalkane" "primary alkyl halide")))
(assert '(hasClassName "secondary halogenalkane chemical referent class*" (setof "secondary halogenoalkane" "secondary haloalkane" "secondary alkyl halide")))
(assert '(hasClassName "tertiary halogenalkane chemical referent class*" (setof "tertiary halogenalkane" "tertiary haloalkane" "tertiary alkyl halide")))
