;;; straight chain amine substances
(assert '(Isa "methanamine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "ethanamine pure chemical substance*" "primary amine substance class"))
(assert '(Isa "propan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "propan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "butan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "butan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "pentan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "pentan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "pentan-3-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "hexan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "hexan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "hexan-3-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "heptan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "heptan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "heptan-3-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "heptan-4-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "octan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "octan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "octan-3-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "octan-4-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "nonan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "nonan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "nonan-3-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "nonan-4-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "nonan-5-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "decan-1-amine pure chemical substance*" "primary amine substance class*"))
(assert '(Isa "decan-2-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "decan-3-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "decan-4-amine pure chemical substance*" "secondary amine substance class*"))
(assert '(Isa "decan-5-amine pure chemical substance*" "secondary amine substance class*"))
;;; straight chain amine molecules
(assert '(Isa "methanamine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "ethanamine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "propan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "propan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "butan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "butan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "pentan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "pentan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "pentan-3-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "hexan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "hexan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "hexan-3-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "hexan-4-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "heptan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "heptan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "heptan-3-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "heptan-4-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "octan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "octan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "octan-3-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "octan-4-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "nonan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "nonan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "nonan-3-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "nonan-4-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "nonan-5-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "decan-1-amine molecular entity*" "primary amine molecular entity class*"))
(assert '(Isa "decan-2-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "decan-3-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "decan-4-amine molecular entity*" "secondary amine molecular entity class*"))
(assert '(Isa "decan-5-amine molecular entity*" "secondary amine molecular entity class*"))
;;; straight chain amine substance names
(assert '(hasSystematicName "methanamine pure chemical substance*" "methanamine"))
(assert '(hasOtherName "methanamine pure chemical substance*" "methylamine"))
(assert '(hasOtherName "methanamine pure chemical substance*" "aminomethane"))
(assert '(hasSystematicName "ethanamine pure chemical substance*" "ethanamine"))
(assert '(hasOtherName "ethanamine pure chemical substance*" "ethylamine"))
(assert '(hasOtherName "ethanamine pure chemical substance*" "aminoethane"))
(assert '(hasSystematicName "propan-1-amine pure chemical substance*" "propan-1-amine"))
(assert '(hasOtherName "propan-1-amine pure chemical substance*" "1-propanamine"))
(assert '(hasOtherName "propan-1-amine pure chemical substance*" "propylamine"))
(assert '(hasOtherName "propan-1-amine pure chemical substance*" "n-propylamine"))
(assert '(hasOtherName "propan-1-amine pure chemical substance*" "1-aminopropane"))
(assert '(hasSystematicName "propan-2-amine pure chemical substance*" "propan-2-amine"))
(assert '(hasOtherName "propan-2-amine pure chemical substance*" "2-propanamine"))
(assert '(hasOtherName "propan-2-amine pure chemical substance*" "isopropylamine"))
(assert '(hasOtherName "propan-2-amine pure chemical substance*" "2-aminopropane"))
(assert '(hasOtherName "propan-2-amine pure chemical substance*" "2-propylamine"))
(assert '(hasSystematicName "butan-1-amine pure chemical substance*" "butan-1-amine"))
(assert '(hasOtherName "butan-1-amine pure chemical substance*" "n-butylamine"))
(assert '(hasOtherName "butan-1-amine pure chemical substance*" "1-aminobutane"))
(assert '(hasOtherName "butan-1-amine pure chemical substance*" "1-butanamine"))
(assert '(hasSystematicName "butan-2-amine pure chemical substance*" "butan-2-amine"))
(assert '(hasOtherName "butan-2-amine pure chemical substance*" "sec-butylamine"))
(assert '(hasOtherName "butan-2-amine pure chemical substance*" "2-aminobutane"))
(assert '(hasOtherName "butan-2-amine pure chemical substance*" "2-butanamine"))
(assert '(hasSystematicName "pentan-1-amine pure chemical substance*" "pentan-1-amine"))
(assert '(hasPreferredIupacName "pentan-1-amine pure chemical substance*" "pentanamine"))
(assert '(hasOtherName "pentan-1-amine pure chemical substance*" "1-aminopentane"))
(assert '(hasOtherName "pentan-1-amine pure chemical substance*" "n-amylamine"))
(assert '(hasSystematicName "pentan-2-amine pure chemical substance*" "pentan-2-amine"))
(assert '(hasOtherName "pentan-2-amine pure chemical substance*" "2-aminopentane"))
(assert '(hasSystematicName "pentan-3-amine pure chemical substance*" "pentan-3-amine"))
(assert '(hasOtherName "pentan-3-amine pure chemical substance*" "3-aminopentane"))
(assert '(hasSystematicName "hexan-1-amine pure chemical substance*" "hexan-1-amine"))
(assert '(hasOtherName "hexan-1-amine pure chemical substance*" "1-aminohexane"))
(assert '(hasOtherName "hexan-1-amine pure chemical substance*" "1-hexanamine"))
(assert '(hasSystematicName "hexan-2-amine pure chemical substance*" "hexan-2-amine"))
(assert '(hasOtherName "hexan-2-amine pure chemical substance*" "2-aminohexane"))
(assert '(hasOtherName "hexan-2-amine pure chemical substance*" "2-hexanamine"))
(assert '(hasSystematicName "hexan-3-amine pure chemical substance*" "hexan-3-amine"))
(assert '(hasOtherName "hexan-3-amine pure chemical substance*" "3-aminohexane"))
(assert '(hasOtherName "hexan-3-amine pure chemical substance*" "3-hexanamine"))
(assert '(hasSystematicName "hexan-4-amine pure chemical substance*" "hexan-4-amine"))
(assert '(hasOtherName "hexan-4-amine pure chemical substance*" "4-hexanamine"))
(assert '(hasOtherName "hexan-4-amine pure chemical substance*" "4-aminohexane"))
(assert '(hasSystematicName "heptan-1-amine pure chemical substance*" "heptan-1-amine"))
(assert '(hasOtherName "heptan-1-amine pure chemical substance*" "1-heptanamine"))
(assert '(hasOtherName "heptan-1-amine pure chemical substance*" "1-aminoheptane"))
(assert '(hasSystematicName "heptan-2-amine pure chemical substance*" "heptan-2-amine"))
(assert '(hasOtherName "heptan-2-amine pure chemical substance*" "2-heptanamine"))
(assert '(hasOtherName "heptan-2-amine pure chemical substance*" "2-aminoheptane"))
(assert '(hasSystematicName "heptan-3-amine pure chemical substance*" "heptan-3-amine"))
(assert '(hasOtherName "heptan-3-amine pure chemical substance*" "3-heptanamine"))
(assert '(hasOtherName "heptan-3-amine pure chemical substance*" "3-aminoheptane"))
(assert '(hasSystematicName "heptan-4-amine pure chemical substance*" "heptan-4-amine"))
(assert '(hasOtherName "heptan-4-amine pure chemical substance*" "4-heptanamine"))
(assert '(hasOtherName "heptan-4-amine pure chemical substance*" "4-aminoheptane"))
(assert '(hasSystematicName "octan-1-amine pure chemical substance*" "octan-1-amine"))
(assert '(hasOtherName "octan-1-amine pure chemical substance*" "1-octanamine"))
(assert '(hasOtherName "octan-1-amine pure chemical substance*" "1-aminooctane"))
(assert '(hasOtherName "octan-1-amine pure chemical substance*" "octylamine"))
(assert '(hasOtherName "octan-1-amine pure chemical substance*" "n-octylamine"))
(assert '(hasSystematicName "octan-2-amine pure chemical substance*" "octan-2-amine"))
(assert '(hasOtherName "octan-2-amine pure chemical substance*" "2-octanamine"))
(assert '(hasOtherName "octan-2-amine pure chemical substance*" "2-aminooctane"))
(assert '(hasOtherName "octan-2-amine pure chemical substance*" "2-octylamine"))
(assert '(hasOtherName "octan-2-amine pure chemical substance*" "sec-octylamine"))
(assert '(hasSystematicName "octan-3-amine pure chemical substance*" "octan-3-amine"))
(assert '(hasOtherName "octan-3-amine pure chemical substance*" "3-octanamine"))
(assert '(hasOtherName "octan-3-amine pure chemical substance*" "3-aminoactane"))
(assert '(hasOtherName "octan-3-amine pure chemical substance*" "3-octylamine"))
(assert '(hasSystematicName "octan-4-amine pure chemical substance*" "octan-4-amine"))
(assert '(hasOtherName "octan-4-amine pure chemical substance*" "4-octanamine"))
(assert '(hasOtherName "octan-4-amine pure chemical substance*" "4-aminooctane"))
(assert '(hasOtherName "octan-4-amine pure chemical substance*" "4-octylamine"))
(assert '(hasSystematicName "nonan-1-amine pure chemical substance*" "nonan-1-amine"))
(assert '(hasOtherName "nonan-1-amine pure chemical substance*" "1-nonanamine"))
(assert '(hasOtherName "nonan-1-amine pure chemical substance*" "1-aminononane"))
(assert '(hasOtherName "nonan-1-amine pure chemical substance*" "1-nonylamine"))
(assert '(hasSystematicName "nonan-2-amine pure chemical substance*" "nonan-2-amine"))
(assert '(hasOtherName "nonan-2-amine pure chemical substance*" "2-nonanamine"))
(assert '(hasOtherName "nonan-2-amine pure chemical substance*" "2-aminononane"))
(assert '(hasOtherName "nonan-2-amine pure chemical substance*" "2-nonylamine"))
(assert '(hasSystematicName "nonan-3-amine pure chemical substance*" "nonan-3-amine"))
(assert '(hasOtherName "nonan-3-amine pure chemical substance*" "3-nonanamine"))
(assert '(hasOtherName "nonan-3-amine pure chemical substance*" "3-aminononane"))
(assert '(hasOtherName "nonan-3-amine pure chemical substance*" "3-nonylamine"))
(assert '(hasSystematicName "nonan-4-amine pure chemical substance*" "nonan-4-amine"))
(assert '(hasOtherName "nonan-4-amine pure chemical substance*" "4-nonanamine"))
(assert '(hasOtherName "nonan-4-amine pure chemical substance*" "4-aminononane"))
(assert '(hasOtherName "nonan-4-amine pure chemical substance*" "4-nonylamine"))
(assert '(hasSystematicName "nonan-5-amine pure chemical substance*" "nonan-5-amine"))
(assert '(hasOtherName "nonan-5-amine pure chemical substance*" "5-nonanamine"))
(assert '(hasOtherName "nonan-5-amine pure chemical substance*" "5-aminononane"))
(assert '(hasOtherName "nonan-5-amine pure chemical substance*" "5-nonylamine"))
(assert '(hasSystematicName "decan-1-amine pure chemical substance*" "decan-1-amine"))
(assert '(hasOtherName "decan-1-amine pure chemical substance*" "1-decanamine"))
(assert '(hasOtherName "decan-1-amine pure chemical substance*" "1-aminodecane"))
(assert '(hasOtherName "decan-1-amine pure chemical substance*" "1-decylamine"))
(assert '(hasSystematicName "decan-2-amine pure chemical substance*" "decan-2-amine"))
(assert '(hasOtherName "decan-2-amine pure chemical substance*" "2-decanamine"))
(assert '(hasOtherName "decan-2-amine pure chemical substance*" "2-aminodecane"))
(assert '(hasOtherName "decan-2-amine pure chemical substance*" "2-decylamine"))
(assert '(hasSystematicName "decan-3-amine pure chemical substance*" "decan-3-amine"))
(assert '(hasOtherName "decan-3-amine pure chemical substance*" "3-decanamine"))
(assert '(hasOtherName "decan-3-amine pure chemical substance*" "3-aminodecane"))
(assert '(hasOtherName "decan-3-amine pure chemical substance*" "3-decylamine"))
(assert '(hasSystematicName "decan-4-amine pure chemical substance*" "decan-4-amine"))
(assert '(hasOtherName "decan-4-amine pure chemical substance*" "4-decanamine"))
(assert '(hasOtherName "decan-4-amine pure chemical substance*" "4-aminodecane"))
(assert '(hasOtherName "decan-4-amine pure chemical substance*" "4-decylamine"))
(assert '(hasSystematicName "decan-5-amine pure chemical substance*" "decan-5-amine"))
(assert '(hasOtherName "decan-5-amine pure chemical substance*" "5-decanamine"))
(assert '(hasOtherName "decan-5-amine pure chemical substance*" "5-aminodecane"))
(assert '(hasOtherName "decan-5-amine pure chemical substance*" "5-decylamine"))
;;; straight chain amine molecule names
(assert '(hasSystematicName "methanamine molecular entity*" "methanamine"))
(assert '(hasOtherName "methanamine pure molecular entity*" "methylamine"))
(assert '(hasOtherName "methanamine pure molecular entity*" "aminomethane"))
(assert '(hasSystematicName "ethanamine molecular entity*" "ethanamine"))
(assert '(hasOtherName "ethanamine pure molecular entity*" "ethylamine"))
(assert '(hasOtherName "ethanamine pure molecular entity*" "aminoethane"))
(assert '(hasSystematicName "propan-1-amine molecular entity*" "propan-1-amine"))
(assert '(hasOtherName "propan-1-amine molecular entity*" "1-propanamine"))
(assert '(hasOtherName "propan-1-amine molecular entity*" "propylamine"))
(assert '(hasOtherName "propan-1-amine molecular entity*" "n-propylamine"))
(assert '(hasOtherName "propan-1-amine molecular entity*" "1-aminopropane"))
(assert '(hasSystematicName "propan-2-amine molecular entity*" "propan-2-amine"))
(assert '(hasOtherName "propan-2-amine molecular entity*" "2-propanamine"))
(assert '(hasOtherName "propan-2-amine molecular entity*" "isopropylamine"))
(assert '(hasOtherName "propan-2-amine molecular entity*" "2-aminopropane"))
(assert '(hasOtherName "propan-2-amine molecular entity*" "2-propylamine"))
(assert '(hasSystematicName "butan-1-amine molecular entity*" "butan-1-amine"))
(assert '(hasOtherName "butan-1-amine molecular entity*" "n-butylamine"))
(assert '(hasOtherName "butan-1-amine molecular entity*" "1-aminobutane"))
(assert '(hasOtherName "butan-1-amine molecular entity*" "1-butanamine"))
(assert '(hasSystematicName "butan-2-amine molecular entity*" "butan-2-amine"))
(assert '(hasOtherName "butan-2-amine molecular entity*" "sec-butylamine"))
(assert '(hasOtherName "butan-2-amine molecular entity*" "2-aminobutane"))
(assert '(hasOtherName "butan-2-amine molecular entity*" "2-butanamine"))
(assert '(hasSystematicName "pentan-1-amine molecular entity*" "pentan-1-amine"))
(assert '(hasPreferredIupacName "pentan-1-amine molecular entity*" "pentanamine"))
(assert '(hasOtherName "pentan-1-amine molecular entity*" "1-aminopentane"))
(assert '(hasOtherName "pentan-1-amine pure chemical substance*" "n-amylamine"))
(assert '(hasSystematicName "pentan-2-amine molecular entity*" "pentan-2-amine"))
(assert '(hasOtherName "pentan-2-amine pure molecular entity*" "2-aminopentane"))
(assert '(hasSystematicName "pentan-3-amine molecular entity*" "pentan-3-amine"))
(assert '(hasOtherName "pentan-3-amine molecular entity*" "3-aminopentane"))
(assert '(hasSystematicName "hexan-1-amine molecular entity*" "hexan-1-amine"))
(assert '(hasOtherName "hexan-1-amine molecular entity*" "1-aminohexane"))
(assert '(hasOtherName "hexan-1-amine molecular entity*" "1-hexanamine"))
(assert '(hasSystematicName "hexan-2-amine molecular entity*" "hexan-2-amine"))
(assert '(hasOtherName "hexan-2-amine molecular entity*" "2-aminohexane"))
(assert '(hasOtherName "hexan-2-amine molecular entity*" "2-hexanamine"))
(assert '(hasSystematicName "hexan-3-amine molecular entity*" "hexan-3-amine"))
(assert '(hasOtherName "hexan-3-amine molecular entity*" "3-aminohexane"))
(assert '(hasOtherName "hexan-3-amine molecular entity*" "3-hexanamine"))
(assert '(hasSystematicName "hexan-4-amine molecular entity*" "hexan-4-amine"))
(assert '(hasOtherName "hexan-4-amine pure chemical substance*" "4-hexanamine"))
(assert '(hasOtherName "hexan-4-amine pure chemical substance*" "4-aminohexane"))
(assert '(hasSystematicName "heptan-1-amine molecular entity*" "heptan-1-amine"))
(assert '(hasOtherName "heptan-1-amine molecular entity*" "1-heptanamine"))
(assert '(hasOtherName "heptan-1-amine molecular entity*" "1-aminoheptane"))
(assert '(hasSystematicName "heptan-2-amine molecular entity*" "heptan-2-amine"))
(assert '(hasOtherName "heptan-2-amine molecular entity*" "2-heptanamine"))
(assert '(hasOtherName "heptan-2-amine molecular entity*" "2-aminoheptane"))
(assert '(hasSystematicName "heptan-3-amine molecular entity*" "heptan-3-amine"))
(assert '(hasOtherName "heptan-3-amine molecular entity*" "3-heptanamine"))
(assert '(hasOtherName "heptan-3-amine molecular entity*" "3-aminoheptane"))
(assert '(hasSystematicName "heptan-4-amine molecular entity*" "heptan-4-amine"))
(assert '(hasOtherName "heptan-4-amine molecular entity*" "4-heptanamine"))
(assert '(hasOtherName "heptan-4-amine molecular entity*" "4-aminoheptane"))
(assert '(hasSystematicName "octan-1-amine molecular entity*" "octan-1-amine"))
(assert '(hasOtherName "octan-1-amine molecular entity*" "1-octanamine"))
(assert '(hasOtherName "octan-1-amine molecular entity*" "1-aminooctane"))
(assert '(hasOtherName "octan-1-amine molecular entity*" "octylamine"))
(assert '(hasOtherName "octan-1-amine molecular entity*" "n-octylamine"))
(assert '(hasSystematicName "octan-2-amine molecular entity*" "octan-2-amine"))
(assert '(hasOtherName "octan-2-amine molecular entity*" "2-octanamine"))
(assert '(hasOtherName "octan-2-amine molecular entity*" "2-aminooctane"))
(assert '(hasOtherName "octan-2-amine molecular entity*" "2-octylamine"))
(assert '(hasOtherName "octan-2-amine molecular entity*" "sec-octylamine"))
(assert '(hasSystematicName "octan-3-amine molecular entity*" "octan-3-amine"))
(assert '(hasOtherName "octan-3-amine molecular entity*" "3-octanamine"))
(assert '(hasOtherName "octan-3-amine molecular entity*" "3-aminoactane"))
(assert '(hasOtherName "octan-3-amine molecular entity*" "3-octylamine"))
(assert '(hasSystematicName "octan-4-amine molecular entity*" "octan-4-amine"))
(assert '(hasOtherName "octan-4-amine molecular entity*" "4-octanamine"))
(assert '(hasOtherName "octan-4-amine molecular entity*" "4-aminooctane"))
(assert '(hasOtherName "octan-4-amine molecular entity*" "4-octylamine"))
(assert '(hasSystematicName "nonan-1-amine molecular entity*" "nonan-1-amine"))
(assert '(hasOtherName "nonan-1-amine molecular entity*" "1-nonanamine"))
(assert '(hasOtherName "nonan-1-amine molecular entity*" "1-aminononane"))
(assert '(hasOtherName "nonan-1-amine molecular entity*" "1-nonylamine"))
(assert '(hasSystematicName "nonan-2-amine molecular entity*" "nonan-2-amine"))
(assert '(hasOtherName "nonan-2-amine molecular entity*" "2-nonanamine"))
(assert '(hasOtherName "nonan-2-amine molecular entity*" "2-aminononane"))
(assert '(hasOtherName "nonan-2-amine molecular entity*" "2-nonylamine"))
(assert '(hasSystematicName "nonan-3-amine molecular entity*" "nonan-3-amine"))
(assert '(hasOtherName "nonan-3-amine molecular entity*" "3-nonanamine"))
(assert '(hasOtherName "nonan-3-amine molecular entity*" "3-aminononane"))
(assert '(hasOtherName "nonan-3-amine molecular entity*" "3-nonylamine"))
(assert '(hasSystematicName "nonan-4-amine molecular entity*" "nonan-4-amine"))
(assert '(hasOtherName "nonan-4-amine molecular entity*" "4-nonanamine"))
(assert '(hasOtherName "nonan-4-amine molecular entity*" "4-aminononane"))
(assert '(hasOtherName "nonan-4-amine molecular entity*" "4-nonylamine"))
(assert '(hasSystematicName "nonan-5-amine molecular entity*" "nonan-5-amine"))
(assert '(hasOtherName "nonan-5-amine molecular entity*" "5-nonanamine"))
(assert '(hasOtherName "nonan-5-amine molecular entity*" "5-aminononane"))
(assert '(hasOtherName "nonan-5-amine molecular entity*" "5-nonylamine"))
(assert '(hasSystematicName "decan-1-amine molecular entity*" "decan-1-amine"))
(assert '(hasOtherName "decan-1-amine molecular entity*" "1-decanamine"))
(assert '(hasOtherName "decan-1-amine molecular entity*" "1-aminodecane"))
(assert '(hasOtherName "decan-1-amine molecular entity*" "1-decylamine"))
(assert '(hasSystematicName "decan-2-amine molecular entity*" "decan-2-amine"))
(assert '(hasOtherName "decan-2-amine molecular entity*" "2-decanamine"))
(assert '(hasOtherName "decan-2-amine molecular entity*" "2-aminodecane"))
(assert '(hasOtherName "decan-2-amine molecular entity*" "2-decylamine"))
(assert '(hasSystematicName "decan-3-amine molecular entity*" "decan-3-amine"))
(assert '(hasOtherName "decan-3-amine molecular entity*" "3-decanamine"))
(assert '(hasOtherName "decan-3-amine molecular entity*" "3-aminodecane"))
(assert '(hasOtherName "decan-3-amine molecular entity*" "3-decylamine"))
(assert '(hasSystematicName "decan-4-amine molecular entity*" "decan-4-amine"))
(assert '(hasOtherName "decan-4-amine molecular entity*" "4-decanamine"))
(assert '(hasOtherName "decan-4-amine molecular entity*" "4-aminodecane"))
(assert '(hasOtherName "decan-4-amine molecular entity*" "4-decylamine"))
(assert '(hasSystematicName "decan-5-amine molecular entity*" "decan-5-amine"))
(assert '(hasOtherName "decan-5-amine molecular entity*" "5-decanamine"))
(assert '(hasOtherName "decan-5-amine molecular entity*" "5-aminodecane"))
(assert '(hasOtherName "decan-5-amine molecular entity*" "5-decylamine"))
