;;; straight chain aldehyde substances
(assert '(Isa "methanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "ethanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "propanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "butanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "pentanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "hexanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "heptanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "octanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "nonanal pure chemical substance*" "aldehyde substance class*"))
(assert '(Isa "decanal pure chemical substance*" "aldehyde substance class*"))
 ;;; straight chain aldehyde molecules
(assert '(Isa "methanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "ethanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "propanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "butanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "pentanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "hexanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "heptanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "octanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "nonanal molecular entity*" "aldehyde molecular entity class*"))
(assert '(Isa "decanal molecular entity*" "aldehyde molecular entity class*"))
;;; straight chain aldehyde substance names
(assert '(hasSystematicName "methanal pure chemical substance*" "methanal"))
(assert '(hasOtherName "methanal pure chemical substance*" "formaldehyde"))
(assert '(hasSystematicName "ethanal pure chemical substance*" "ethanal"))
(assert '(hasSystematicName "propanal pure chemical substance*" "propanal"))
(assert '(hasSystematicName "butanal pure chemical substance*" "butanal"))
(assert '(hasSystematicName "pentanal pure chemical substance*" "pentanal"))
(assert '(hasSystematicName "hexanal pure chemical substance*" "hexanal"))
(assert '(hasSystematicName "heptanal pure chemical substance*" "heptanal"))
(assert '(hasSystematicName "octanal pure chemical substance*" "octanal"))
(assert '(hasSystematicName "nonanal pure chemical substance*" "nonanal"))
(assert '(hasSystematicName "decanal pure chemical substance*" "decanal"))
;;; straight chain aldehyde molecular entity names
(assert '(hasSystematicName "methanal molecular entity*" "methanal"))
(assert '(hasOtherName "methanal molecular entity*" "formaldehyde"))
(assert '(hasSystematicName "ethanal molecular entity*" "ethanal"))
(assert '(hasSystematicName "propanal molecular entity*" "propanal"))
(assert '(hasSystematicName "butanal molecular entity*" "butanal"))
(assert '(hasSystematicName "pentanal molecular entity*" "pentanal"))
(assert '(hasSystematicName "hexanal molecular entity*" "hexanal"))
(assert '(hasSystematicName "heptanal molecular entity*" "heptanal"))
(assert '(hasSystematicName "octanal molecular entity*" "octanal"))
(assert '(hasSystematicName "nonanal molecular entity*" "nonanal"))
(assert '(hasSystematicName "decanal molecular entity*" "decanal"))
