;;; straight chain alkyne substances
(assert '(Isa "ethyne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "propyne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "but-1-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "but-2-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "pent-1-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "pent-2-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "hex-1-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "hex-2-yne pure chemical substance*" "alkhashasyne substance class*"))
(assert '(Isa "hex-3-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "hept-1-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "hept-2-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "hept-3-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "oct-1-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "oct-2-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "oct-3-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "oct-4-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "non-1-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "non-2-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "non-3-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "non-4-yne pure chemical substance*" "alkyne substance class*"))
(assert '(Isa "dec-5-yne pure chemical substance*" "alkyne substance class*"))
;;; straight chain alkyne molecules
(assert '(Isa "ethyne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "propyne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "but-1-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "but-2-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "pent-1-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "pent-2-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "hex-1-yne molecular entity**" "alkyne molecular entity class*"))
(assert '(Isa "hex-2-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "hex-3-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "hept-1-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "hept-2-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "hept-3-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "oct-1-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "oct-2-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "oct-3-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "oct-4-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "non-1-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "non-2-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "non-3-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "non-4-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "dec-1-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "dec-2-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "dec-3-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "dec-4-yne molecular entity*" "alkyne molecular entity class*"))
(assert '(Isa "dec-5-yne molecular entity*" "alkyne molecular entity class*"))
;;; alkyne molecular entity names
(assert '(hasSystematicName "ethyne pure chemical substance*" "ethyne"))
(assert '(hasAcceptableCommonName "ethyne pure chemical substance*" "acetylene"))
(assert '(hasSystematicName "propyne pure chemical substance*" "propyne"))
(assert '(hasSystematicName "but-1-yne pure chemical substance*" "but-1-yne"))
(assert '(hasSystematicName "but-2-yne pure chemical substance*" "but-2-yne"))
(assert '(hasSystematicName "pent-1-yne pure chemical substance*" "pent-1-yne"))
(assert '(hasSystematicName "pent-2-yne pure chemical substance*" "pent-2-yne"))
(assert '(hasSystematicName "hex-1-yne pure chemical substance*" "hex-1-yne"))
(assert '(hasSystematicName "hex-2-yne pure chemical substance*" "hex-2-yne"))
(assert '(hasSystematicName "hex-3-yne pure chemical substance*" "hex-3-yne"))
(assert '(hasSystematicName "hept-1-yne pure chemical substance*" "hept-1-yne"))
(assert '(hasSystematicName "hept-2-yne pure chemical substance*" "hept-2-yne"))
(assert '(hasSystematicName "hept-3-yne pure chemical substance*" "hept-3-yne"))
(assert '(hasSystematicName "oct-1-yne pure chemical substance*" "oct-1-yne"))
(assert '(hasSystematicName "oct-2-yne pure chemical substance*" "oct-2-yne"))
(assert '(hasSystematicName "oct-3-yne pure chemical substance*" "oct-3-yne"))
(assert '(hasSystematicName "oct-4-yne pure chemical substance*" "oct-4-yne"))
(assert '(hasSystematicName "non-1-yne pure chemical substance*" "non-1-yne"))
(assert '(hasSystematicName "non-2-yne pure chemical substance*" "non-2-yne"))
(assert '(hasSystematicName "non-3-yne pure chemical substance*" "non-3-yne"))
(assert '(hasSystematicName "dec-4-yne pure chemical substance*" "non-4-yne"))
(assert '(hasSystematicName "dec-1-yne pure chemical substance*" "dec-1-yne"))
(assert '(hasSystematicName "dec-2-yne pure chemical substance*" "dec-2-yne"))
(assert '(hasSystematicName "dec-3-yne pure chemical substance*" "dec-3-yne"))
(assert '(hasSystematicName "dec-4-yne pure chemical substance*" "dec-4-yne"))
(assert '(hasSystematicName "dec-5-yne pure chemical substance*" "dec-5-yne"))
