;;; straight chain alkene substances(assert '(Isa "ethene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "propene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "but-1-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "but-2-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "pent-1-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "pent-2-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "hex-1-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "hex-2-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "hex-3-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "hep-1-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "hep-2-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "hep-3-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "oct-1-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "oct-2-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "oct-3-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "oct-4-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "non-1-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "non-2-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "non-3-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "non-4-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "dec-1-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "dec-2-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "dec-3-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "dec-4-ene pure chemical substance*" "alkene substance class*"))
(assert '(Isa "dec-5-ene pure chemical substance*" "alkene substance class*"))
;;; straight chain alkene molecules
(assert '(Isa "ethene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "propene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "but-1-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "but-2-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "pent-1-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "pent-2-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "hex-1-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "hex-2-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "hex-3-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "hep-1-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "hep-2-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "hep-3-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "oct-1-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "oct-2-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "oct-3-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "oct-4-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "non-1-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "non-2-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "non-3-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "non-4-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "dec-1-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "dec-2-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "dec-3-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "dec-4-ene molecular entity*" "alkene molecular entity class*"))
(assert '(Isa "dec-5-ene molecular entity*" "alkene molecular entity class*"))
;;; alkene substance names
(assert '(hasSystematicName "ethene pure molecular substance*" "ethene"))
(assert '(hasSystematicName "propene pure molecular substance*" "propene"))
(assert '(hasSystematicName "but-1-ene pure molecular substance*" "but-1-ene"))
(assert '(hasSystematicName "but-2-ene pure molecular substance*" "but-2-ene"))
(assert '(hasSystematicName "pent-1-ene pure molecular substance*" "pent-1-ene"))
(assert '(hasSystematicName "pent-2-ene pure molecular substance*" "pent-2-ene"))
(assert '(hasSystematicName "hex-1-ene pure molecular substance*" "hex-1-ene"))
(assert '(hasSystematicName "hex-2-ene pure molecular substance*" "hex-2-ene"))
(assert '(hasSystematicName "hex-3-ene pure molecular substance*" "hex-3-ene"))
(assert '(hasSystematicName "hep-1-ene pure molecular substance*" "hep-1-ene"))
(assert '(hasSystematicName "hep-2-ene pure molecular substance*" "hep-2-ene"))
(assert '(hasSystematicName "hep-3-ene pure molecular substance*" "hep-3-ene"))
(assert '(hasSystematicName "oct-1-ene pure molecular substance*" "oct-1-ene"))
(assert '(hasSystematicName "oct-2-ene pure molecular substance*" "oct-2-ene"))
(assert '(hasSystematicName "oct-3-ene pure molecular substance*" "oct-3-ene"))
(assert '(hasSystematicName "oct-4-ene pure molecular substance*" "oct-4-ene"))
(assert '(hasSystematicName "non-1-ene pure molecular substance*" "non-1-ene"))
(assert '(hasSystematicName "non-2-ene pure molecular substance*" "non-2-ene"))
(assert '(hasSystematicName "non-3-ene pure molecular substance*" "non-3-ene"))
(assert '(hasSystematicName "non-4-ene pure molecular substance*" "non-4-ene"))
(assert '(hasSystematicName "dec-1-ene pure molecular substance*" "dec-1-ene"))
(assert '(hasSystematicName "dec-2-ene pure molecular substance*" "dec-2-ene"))
(assert '(hasSystematicName "dec-3-ene pure molecular substance*" "dec-3-ene"))
(assert '(hasSystematicName "dec-4-ene pure molecular substance*" "dec-4-ene"))
(assert '(hasSystematicName "dec-5-ene pure molecular substance*" "dec-5-ene"))
;;; alkene molecule names
(assert '(hasSystematicName "ethene molecular entity*" "ethene"))
(assert '(hasSystematicName "propene molecular entity*" "propene"))
(assert '(hasSystematicName "but-1-ene molecular entity*" "but-1-ene"))
(assert '(hasSystematicName "but-2-ene molecular entity*" "but-2-ene"))
(assert '(hasSystematicName "pent-1-ene molecular entity*" "pent-1-ene"))
(assert '(hasSystematicName "pent-2-ene molecular entity*" "pent-2-ene"))
(assert '(hasSystematicName "hex-1-ene molecular entity*" "hex-1-ene"))
(assert '(hasSystematicName "hex-2-ene molecular entity*" "hex-2-ene"))
(assert '(hasSystematicName "hex-3-ene molecular entity*" "hex-3-ene"))
(assert '(hasSystematicName "hep-1-ene molecular entity*" "hep-1-ene"))
(assert '(hasSystematicName "hep-2-ene molecular entity*" "hep-2-ene"))
(assert '(hasSystematicName "hep-3-ene molecular entity*" "hep-3-ene"))
(assert '(hasSystematicName "oct-1-ene molecular entity*" "oct-1-ene"))
(assert '(hasSystematicName "oct-2-ene molecular entity*" "oct-2-ene"))
(assert '(hasSystematicName "oct-3-ene molecular entity*" "oct-3-ene"))
(assert '(hasSystematicName "oct-4-ene molecular entity*" "oct-4-ene"))
(assert '(hasSystematicName "non-1-ene molecular entity*" "non-1-ene"))
(assert '(hasSystematicName "non-2-ene molecular entity*" "non-2-ene"))
(assert '(hasSystematicName "non-3-ene molecular entity*" "non-3-ene"))
(assert '(hasSystematicName "non-4-ene molecular entity*" "non-4-ene"))
(assert '(hasSystematicName "dec-1-ene molecular entity*" "dec-1-ene"))
(assert '(hasSystematicName "dec-2-ene molecular entity*" "dec-2-ene"))
(assert '(hasSystematicName "dec-3-ene molecular entity*" "dec-3-ene"))
(assert '(hasSystematicName "dec-4-ene molecular entity*" "dec-4-ene"))
(assert '(hasSystematicName "dec-5-ene molecular entity*" "dec-5-ene"))
