;;; straight chain alcohol substances
(assert '(Isa "methanol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "ethanol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "propan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "propan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "butan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "butan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "pentan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "pentan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "hexan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "hexan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "hexan-3-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "heptan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "heptan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "heptan-3-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "heptan-4-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "octan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "octan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "octan-3-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "octan-4-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "nonan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "nonan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "nonan-3-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "nonan-4-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "nonan-5-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "decan-1-ol pure chemical substance*" "primary alkanol substance class*"))
(assert '(Isa "decan-2-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "decan-3-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "decan-4-ol pure chemical substance*" "secondary alkanol substance class*"))
(assert '(Isa "decan-5-ol pure chemical substance*" "secondary alkanol substance class*"))
;;; straight chain alcohol molecules
(assert '(Isa "methanol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "ethanol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "propan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "propan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "butan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "butan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "pentan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "pentan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "pentan-3-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "hexan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "hexan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "hexan-3-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "heptan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "heptan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "heptan-3-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "heptan-4-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "octan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "octan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "octan-3-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "octan-4-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "nonan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "nonan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "nonan-3-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "nonan-4-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "nonan-5-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "decan-1-ol molecular entity*" "primary alkanol molecular entity class*"))
(assert '(Isa "decan-2-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "decan-3-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "decan-4-ol molecular entity*" "secondary alkanol molecular entity class*"))
(assert '(Isa "decan-5-ol molecular entity*" "secondary alkanol molecular entity class*"))
;;; alkanol substance names
(assert '(hasSystematicName "methanol pure chemical substance*" "methanol"))
(assert '(hasSystematicName "ethanol pure chemical substance*" "ethanol"))
(assert '(hasSystematicName "propan-1-ol pure chemical substance*" "propan-1-ol"))
(assert '(hasOtherName "propan-1-ol pure chemical substance*" "propanol"))
(assert '(hasSystematicName "propan-2-ol pure chemical substance*" "hasSystematicName"))
(assert '(hasSystematicName "butan-1-ol pure chemical substance*" "butan-1-ol"))
(assert '(hasOtherName "butan-1-ol pure chemical substance*" "butanol"))
(assert '(hasSystematicName "butan-2-ol pure chemical substance*" "butan-2-ol"))
(assert '(hasSystematicName "pentan-1-ol pure chemical substance*" "pentan-1-ol"))
(assert '(hasOtherName "pentan-1-ol pure chemical substance*" "pentanol"))
(assert '(hasSystematicName "pentan-2-ol pure chemical substance*" "pentan-2-ol"))
(assert '(hasSystematicName "hexan-1-ol pure chemical substance*" "hexan-1-ol"))
(assert '(hasSystematicName "hexan-1-ol pure chemical substance*" "hexanol"))
(assert '(hasSystematicName "hexan-2-ol pure chemical substance*" "hexan-2-ol"))
(assert '(hasSystematicName "hexan-3-ol pure chemical substance*" "hexan-3-ol"))
(assert '(hasSystematicName "heptan-1-ol pure chemical substance*" "heptan-1-ol"))
(assert '(hasOtherName "heptan-1-ol pure chemical substance*" "heptanol"))
(assert '(hasSystematicName "heptan-2-ol pure chemical substance*" "heptan-2-ol"))
(assert '(hasSystematicName "heptan-3-ol pure chemical substance*" "heptan-3-ol"))
(assert '(hasSystematicName "heptan-4-ol pure chemical substance*" "heptan-4-ol"))
(assert '(hasSystematicName "octan-1-ol pure chemical substance*" "octan-1-ol"))
(assert '(hasSystematicName "octan-1-ol pure chemical substance*" "octanol"))
(assert '(hasSystematicName "octan-2-ol pure chemical substance*" "octan-2-ol"))
(assert '(hasSystematicName "octan-3-ol pure chemical substance*" "octan-3-ol"))
(assert '(hasSystematicName "octan-4-ol pure chemical substance*" "octan-4-ol"))
(assert '(hasSystematicName "nonan-1-ol pure chemical substance*" "nonan-1-ol"))
(assert '(hasOtherName "nonan-1-ol pure chemical substance*" "nonanol"))
(assert '(hasSystematicName "nonan-2-ol pure chemical substance*" "nonan-2-ol"))
(assert '(hasSystematicName "nonan-3-ol pure chemical substance*" "nonan-3-ol"))
(assert '(hasSystematicName "nonan-4-ol pure chemical substance*" "nonan-4-ol"))
(assert '(hasSystematicName "nonan-5-ol pure chemical substance*" "nonan-5-ol"))
(assert '(hasSystematicName "decan-1-ol pure chemical substance*" "decan-1-ol"))
(assert '(hasOtherName "decan-1-ol pure chemical substance*" "decanol"))
(assert '(hasSystematicName "decan-2-ol pure chemical substance*" "decan-2-ol"))
(assert '(hasSystematicName "decan-3-ol pure chemical substance*" "decan-3-ol"))
(assert '(hasSystematicName "decan-4-ol pure chemical substance*" "decan-4-ol"))
(assert '(hasSystematicName "decan-5-ol pure chemical substance*" "decan-5-ol"))
;;; alkanol molecular entity names
(assert '(hasSystematicName "methanol molecular entity*" "methanol"))
(assert '(hasSystematicName "ethanol molecular entity*" "ethanol"))
(assert '(hasSystematicName "propan-1-ol molecular entity*" "propan-1-ol"))
(assert '(hasOtherName "propan-1-ol molecular entity*" "propanol"))
(assert '(hasSystematicName "propan-2-ol molecular entity*" "propan-2-ol"))
(assert '(hasSystematicName "butan-1-ol molecular entity*" "butan-1-ol"))
(assert '(hasOtherName "butan-1-ol molecular entity*" "butan-1-ol"))
(assert '(hasSystematicName "butan-2-ol molecular entity*" "butan-2-ol"))
(assert '(hasSystematicName "pentan-1-ol molecular entity*" "pentan-1-ol"))
(assert '(hasOtherName "pentan-1-ol molecular entity*" "pentanol"))
(assert '(hasSystematicName "pentan-2-ol molecular entity*" "pentan-2-ol"))
(assert '(hasSystematicName "pentan-3-ol molecular entity*" "pentan-3-ol"))
(assert '(hasSystematicName "hexan-1-ol molecular entity*" "hexan-1-ol"))
(assert '(hasOtherName "hexan-1-ol molecular entity*" "hexanol"))
(assert '(hasSystematicName "hexan-2-ol molecular entity*" "hexan-2-ol"))
(assert '(hasSystematicName "hexan-3-ol molecular entity*" "hexan-3-ol"))
(assert '(hasSystematicName "heptan-1-ol molecular entity*" "heptan-1-ol"))
(assert '(hasOtherName "heptan-1-ol molecular entity*" "heptanol"))
(assert '(hasSystematicName "heptan-2-ol molecular entity*" "heptan-2-ol"))
(assert '(hasSystematicName "heptan-3-ol molecular entity*" "heptan-3-ol"))
(assert '(hasSystematicName "heptan-4-ol molecular entity*" "heptan-4-ol"))
(assert '(hasSystematicName "octan-1-ol molecular entity*" "octan-1-ol"))
(assert '(hasOtherName "octan-1-ol molecular entity*" "octanol"))
(assert '(hasSystematicName "octan-2-ol molecular entity*" "octan-2-ol"))
(assert '(hasSystematicName "octan-3-ol molecular entity*" "octan-3-ol"))
(assert '(hasSystematicName "octan-4-ol molecular entity*" "octan-4-ol"))
(assert '(hasSystematicName "nonan-1-ol molecular entity*" "nonan-1-ol"))
(assert '(hasOtherName "nonan-1-ol molecular entity*" "nonanol"))
(assert '(hasSystematicName "nonan-2-ol molecular entity*" "nonan-2-ol"))
(assert '(hasSystematicName "nonan-3-ol molecular entity*" "nonan-3-ol"))
(assert '(hasSystematicName "nonan-4-ol molecular entity*" "nonan-4-ol"))
(assert '(hasSystematicName "nonan-5-ol molecular entity*" "nonan-5-ol"))
(assert '(hasSystematicName "decan-1-ol molecular entity*" "decan-1-ol"))
(assert '(hasOtherName "decan-1-ol molecular entity*" "decanol"))
(assert '(hasSystematicName "decan-2-ol molecular entity*" "decan-2-ol"))
(assert '(hasSystematicName "decan-3-ol molecular entity*" "decan-3-ol"))
