;;; straight chain ketone substances
(assert '(Isa "propan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "butan-1-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "butan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "pentan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "pentan-3-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "hexan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "hexan-3-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "heptan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "heptan-3-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "heptan-4-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "octan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "octan-3-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "octan-4-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "nonan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "nonan-3-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "nonan-4-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "nonan-5-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "decan-2-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "decan-3-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "decan-4-one pure chemical substance*" "ketone substance class*"))
(assert '(Isa "decan-5-one pure chemical substance*" "ketone substance class*"))
;;; straight chain ketone molecules
(assert '(Isa "propan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "butan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "pentan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "pentan-3-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "hexan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "hexan-3-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "heptan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "heptan-3-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "heptan-4-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "octan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "octan-3-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "octan-4-one molecular entity*" "ketone molecular entity class"))
(assert '(Isa "nonan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "nonan-3-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "nonan-4-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "nonan-5-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "decan-2-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "decan-3-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "decan-4-one molecular entity*" "ketone molecular entity class*"))
(assert '(Isa "decan-5-one molecular entity*" "ketone molecular entity class*"))
;;; straight chain ketone substance names
(assert '(hasSystematicName "propan-2-one pure chemical substance*" "propan-2-one"))
(assert '(hasOtherName "propan-2-one pure chemical substance*" "propanone"))
(assert '(hasOtherName "propan-2-one pure chemical substance*" "acetone"))
(assert '(hasSystematicName "butan-2-one pure chemical substance*" "butan-2-one"))
(assert '(hasOtherName "butan-2-one pure chemical substance*" "butanone"))
(assert '(hasSystematicName "pentan-2-one pure chemical substance*" "pentan-2-one"))
(assert '(hasSystematicName "pentan-3-one pure chemical substance*" "pentan-3-one"))
(assert '(hasOtherName "pentan-2-one pure chemical substance*" "pentanone"))
(assert '(hasOtherName "pentan-3-one pure chemical substance*" "pentanone"))
(assert '(hasSystematicName "hexan-2-one pure chemical substance*" "hexan-2-one"))
(assert '(hasSystematicName "hexan-3-one pure chemical substance*" "hexan-3-one"))
(assert '(hasOtherName "hexan-2-one pure chemical substance*" "hexanone"))
(assert '(hasOtherName "hexan-3-one pure chemical substance*" "hexanone"))
(assert '(hasSystematicName "heptan-2-one pure chemical substance*" "heptan-2-one"))
(assert '(hasSystematicName "heptan-3-one pure chemical substance*" "heptan-3-one"))
(assert '(hasSystematicName "heptan-4-one pure chemical substance*" "heptan-4-one"))
(assert '(hasOtherName "heptan-2-one pure chemical substance*" "heptanone"))
(assert '(hasOtherName "heptan-3-one pure chemical substance*" "heptanone"))
(assert '(hasOtherName "heptan-4-one pure chemical substance*" "heptanone"))
(assert '(hasSystematicName "octan-2-one pure chemical substance*" "octan-2-one"))
(assert '(hasSystematicName "octan-3-one pure chemical substance*" "octan-3-one"))
(assert '(hasSystematicName "octan-4-one pure chemical substance*" "octan-4-one"))
(assert '(hasOtherName "octan-2-one pure chemical substance*" "octanone"))
(assert '(hasOtherName "octan-3-one pure chemical substance*" "octanone"))
(assert '(hasOtherName "octan-4-one pure chemical substance*" "octanone"))
(assert '(hasSystematicName "nonan-2-one pure chemical substance*" "nonan-2-one"))
(assert '(hasSystematicName "nonan-3-one pure chemical substance*" "nonan-3-one"))
(assert '(hasSystematicName "nonan-4-one pure chemical substance*" "nonan-4-one"))
(assert '(hasSystematicName "nonan-5-one pure chemical substance*" "nonan-5-one"))
(assert '(hasOtherName "nonan-2-one pure chemical substance*" "nonanone"))
(assert '(hasOtherName "nonan-3-one pure chemical substance*" "nonanone")) 
(assert '(hasOtherName "nonan-4-one pure chemical substance*" "nonanone"))
(assert '(hasOtherName "nonan-5-one pure chemical substance*" "nonanone"))
(assert '(hasSystematicName "decan-2-one pure chemical substance*" "decan-2-one"))
(assert '(hasSystematicName "decan-3-one pure chemical substance*" "decan-3-one"))
(assert '(hasSystematicName "decan-4-one pure chemical substance*" "decan-4-one"))
(assert '(hasSystematicName "decan-5-one pure chemical substance*" "decan-5-one"))
(assert '(hasOtherName "decan-2-one pure chemical substance*" "decanone"))
(assert '(hasOtherName "decan-3-one pure chemical substance*" "decanone"))
(assert '(hasOtherName "decan-4-one pure chemical substance*" "decanone"))
(assert '(hasOtherName "decan-5-one pure chemical substance*" "decanone"))
;;; straight chain ketone molecule names
(assert '(hasSystematicName "propan-2-one molecular entity*" "propan-2-one"))
(assert '(hasOtherName "propan-2-one molecular entity*" "propanone"))
(assert '(hasOtherName "propan-2-one molecular entity*" "acetone"))
(assert '(hasOtherName "propan-2-one molecular entity*" "dimethylketone"))
(assert '(hasSystematicName "butan-2-one molecular entity*" "butan-2-one"))
(assert '(hasOtherName "butan-2-one molecular entity*" "butanone"))
(assert '(hasSystematicName "pentan-2-one molecular entity*" "pentan-2-one"))
(assert '(hasSystematicName "pentan-3-one molecular entity*" "pentan-3-one"))
(assert '(hasOtherName "pentan-2-one molecular entity*" "pentanone"))
(assert '(hasOtherName "pentan-3-one molecular entity*" "pentanone"))
(assert '(hasSystematicName "hexan-2-one molecular entity*" "hexan-2-one"))
(assert '(hasSystematicName "hexan-3-one molecular entity*" "hexan-3-one"))
(assert '(hasOtherName "hexan-2-one molecular entity*" "hexanone"))
(assert '(hasOtherName "hexan-3-one molecular entity*" "hexanone"))
(assert '(hasSystematicName "heptan-2-one molecular entity*" "heptan-2-one"))
(assert '(hasSystematicName "heptan-3-one molecular entity*" "heptan-3-one"))
(assert '(hasSystematicName "heptan-4-one molecular entity*" "heptan-4-one"))
(assert '(hasOtherName "heptan-2-one molecular entity*" "heptanone"))
(assert '(hasOtherName "heptan-3-one molecular entity*" "heptanone"))
(assert '(hasOtherName "heptan-4-one molecular entity*" "heptanone"))
(assert '(hasSystematicName "octan-2-one molecular entity*" "octan-2-one"))
(assert '(hasSystematicName "octan-3-one molecular entity*" "octan-3-one"))
(assert '(hasSystematicName "octan-4-one molecular entity*" "octan-4-one"))
(assert '(hasOtherName "octan-2-one molecular entity*" "octanone"))
(assert '(hasOtherName "octan-3-one molecular entity*" "octanone"))
(assert '(hasOtherName "octan-4-one molecular entity*" "octanone"))
(assert '(hasSystematicName "nonan-2-one molecular entity*" "nonan-2-one"))
(assert '(hasSystematicName "nonan-3-one molecular entity*" "nonan-3-one"))
(assert '(hasSystematicName "nonan-4-one molecular entity*" "nonan-4-one"))
(assert '(hasSystematicName "nonan-5-one molecular entity*" "nonan-5-one"))
(assert '(hasOtherName "nonan-2-one molecular entity*" "nonanone"))
(assert '(hasOtherName "nonan-3-one molecular entity*" "nonanone"))
(assert '(hasOtherName "nonan-4-one molecular entity*" "nonanone"))
(assert '(hasOtherName "nonan-5-one molecular entity*" "nonanone"))
(assert '(hasSystematicName "decan-2-one molecular entity*" "decan-2-one"))
(assert '(hasSystematicName "decan-3-one molecular entity*" "decan-3-one"))
(assert '(hasSystematicName "decan-4-one molecular entity*" "decan-4-one"))
(assert '(hasSystematicName "decan-5-one molecular entity*" "decan-5-one"))
(assert '(hasOtherName "decan-2-one molecular entity*" "decanone"))
(assert '(hasOtherName "decan-3-one molecular entity*" "decanone"))
(assert '(hasOtherName "decan-4-one molecular entity*" "decanone"))
(assert '(hasOtherName "decan-5-one molecular entity*" "decanone"))
