;;; straight chain carboxylic acid substances  
(assert '(Isa "methanoic acid pure chemical substance*" "carboxylic acid substance class*"))           
(assert '(Isa "ethanoic acid pure chemical substance*" "carboxylic acid substance class*"))            
(assert '(Isa "propanoic acid pure chemical substance*" "carboxylic acid substance class*"))           
(assert '(Isa "butanoic acid pure chemical substance*" "carboxylic acid substance class*"))            
(assert '(Isa "pentanoic acid pure chemical substance*" "carboxylic acid substance class*"))           
(assert '(Isa "hexanoic acid pure chemical substance*" "carboxylic acid substance class*"))            
(assert '(Isa "heptanoic acid pure chemical substance*" "carboxylic acid substance class*"))           
(assert '(Isa "octanoic acid pure chemical substance*" "carboxylic acid substance class*"))            
(assert '(Isa "nonanoic acid pure chemical substance*" "carboxylic acid substance class*"))            
(assert '(Isa "decanoic acid pure chemical substance*" "carboxylic acid substance class*"))
;;; straight chain carboxylic acid molecules
(assert '(Isa "methanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "ethanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "propanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "butanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "pentanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "hexanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "heptanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "octanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "nonanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
(assert '(Isa "decanoic acid molecular entity*" "carboxylic acid molecular entity class*"))
;;; straight chain carboxylic acid substance names
(assert '(hasSystematicName "methanoic acid pure chemical substance*" "methanoic acid"))
(assert '(hasOtherName "methanoic acid pure chemical substance*" "formic acid"))
(assert '(hasSystematicName "ethanoic acid pure chemical substance*" "ethanoic acid"))
(assert '(hasOtherName "ethanoic acid pure chemical substance*" "acetic acid"))
(assert '(hasSystematicName "propanoic acid pure chemical substance*" "propanoic acid"))
(assert '(hasOtherName "propanoic acid pure chemical substance*" "propionic acid"))
(assert '(hasSystematicName "butanoic acid pure chemical substance*" "butanoic acid"))
(assert '(hasOtherName "butanoic acid molecular entity*" "butyric acid"))
(assert '(hasSystematicName "pentanoic acid pure chemical substance*" "pentanoic acid"))
(assert '(hasOtherName "pentanoic acid pure chemical substance*" "valeric acid"))
(assert '(hasSystematicName "hexanoic acid pure chemical substance*" "hexanoic acid"))
(assert '(hasOtherName "hexanoic acid molecular entity*" "caproic acid"))
(assert '(hasSystematicName "heptanoic acid pure chemical substance*" "heptanoic acid"))
(assert '(hasOtherName "heptanoic acid pure chemical substance*" "valeric acid"))
(assert '(hasSystematicName "octanoic acid pure chemical substance*" "octanoic acid"))
(assert '(hasOtherName "octanoic acid pure chemical substance*" "caprylic acid"))
(assert '(hasSystematicName "nonanoic acid pure chemical substance*" "nonanoic acid"))
(assert '(hasOtherName "nonanoic acid pure chemical substance*" "pelargonic acid"))
(assert '(hasSystematicName "decanoic acid pure chemical substance*" "decanoic acid"))
(assert '(hasOtherName "decanoic acid pure chemical substance*" "capric acid"))
;;; straight chain carboxylic acid molecule names
(assert '(hasSystematicName "methanoic acid molecular entity*" "methanoic acid"))
(assert '(hasOtherName "methanoic acid molecular entity*" "formic acid"))
(assert '(hasSystematicName "ethanoic acid molecular entity*" "ethanoic acid"))
(assert '(hasOtherName "ethanoic acid molecular entity*" "acetic acid"))
(assert '(hasSystematicName "propanoic acid molecular entity*" "propanoic acid"))
(assert '(hasOtherName "propanoic acid molecular entity*" "propionic acid"))
(assert '(hasSystematicName "butanoic acid molecular entity*" "butanoic acid"))
(assert '(hasOtherName "butanoic acid molecular entity*" "butyric acid"))
(assert '(hasSystematicName "pentanoic acid molecular entity*" "pentanoic acid"))
(assert '(hasOtherName "pentanoic acid molecular entity*" "valeric acid"))
(assert '(hasSystematicName "hexanoic acid molecular entity*" "hexanoic acid"))
(assert '(hasSystematicName "hexanoic acid molecular entity*" "caproic acid"))
(assert '(hasSystematicName "heptanoic acid molecular entity*" "heptanoic acid"))
(assert '(hasOtherName "heptanoic acid molecular entity*" "enanthic acid"))
(assert '(hasSystematicName "octanoic acid molecular entity*" "octanoic acid"))
(assert '(hasOtherName "octanoic acid molecular entity*" "caprylic acid"))
(assert '(hasSystematicName "nonanoic acid molecular entity*" "nonanoic acid"))
(assert '(hasOtherName "nonanoic acid molecular entity*" "pelargonic acid"))
(assert '(hasSystematicName "decanoic acid molecular entity*" "decanoic acid"))
(assert '(hasOtherName "decanoic acid molecular entity*" "capric acid"))
