 (assert '(HasPhysicalQuantity "hydrogen element*" "relative atomic mass*" "1.008"))
 (assert '(HasPhysicalQuantity "helium element*" "relative atomic mass*" "4.0026"))
 (assert '(HasPhysicalQuantity "lithium element*" "relative atomic mass*" "6.94"))
 (assert '(HasPhysicalQuantity "beryllium element*" "relative atomic mass*" "9.0122"))
 (assert '(HasPhysicalQuantity "boron element*" "relative atomic mass*" "10.81"))
 (assert '(HasPhysicalQuantity "carbon element*" "relative atomic mass*" "12.011"))
 (assert '(HasPhysicalQuantity "nitrogen element*" "relative atomic mass*" "14.007"))
 (assert '(HasPhysicalQuantity "oxygen element*" "relative atomic mass*" "15.999"))
 (assert '(HasPhysicalQuantity "fluorine element*" "relative atomic mass*" "18.998"))
 (assert '(HasPhysicalQuantity "neon element*" "relative atomic mass*" "20.180"))
 (assert '(HasPhysicalQuantity "sodium element*" "relative atomic mass*" "22.990"))
 (assert '(HasPhysicalQuantity "magnesium element*" "relative atomic mass*" "24.305"))
 (assert '(HasPhysicalQuantity "aluminium element*" "relative atomic mass*" "26.982"))
 (assert '(HasPhysicalQuantity "silicon element*" "relative atomic mass*" "28.085"))
 (assert '(HasPhysicalQuantity "phosphorus element*" "relative atomic mass*" "30.974"))
 (assert '(HasPhysicalQuantity "sulfur element*" "relative atomic mass*" "32.06"))
 (assert '(HasPhysicalQuantity "chlorine element*" "relative atomic mass*" "35.45"))
 (assert '(HasPhysicalQuantity "argon element*" "relative atomic mass*" "39.948"))
 (assert '(HasPhysicalQuantity "potassium element*" "relative atomic mass*" "39.098"))
 (assert '(HasPhysicalQuantity "calcium element*" "relative atomic mass*" "40.078"))
 (assert '(HasPhysicalQuantity "scandium element*" "relative atomic mass*" "44.956"))
 (assert '(HasPhysicalQuantity "titanium element*" "relative atomic mass*" "47.867"))
 (assert '(HasPhysicalQuantity "vanadium element*" "relative atomic mass*" "50.942"))
 (assert '(HasPhysicalQuantity "chromium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "manganese  element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "iron element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "cobalt element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "nickel element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "copper element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "zinc element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "gallium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "germanium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "arsenic element*" "semi-metal class"))
 (assert '(HasPhysicalQuantity "selenium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "bromine element*" ""))
 (assert '(HasPhysicalQuantity "krypton element*" ""))
 (assert '(HasPhysicalQuantity "rubidium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "strontium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "yttrium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "zirconium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "niobium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "molybdenum element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "technetium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "ruthenium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "rhodium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "palladium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "silver element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "cadmium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "indium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "tin element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "antimony element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "tellurium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "iodine element*" ""))
 (assert '(HasPhysicalQuantity "xenon element*" ""))
 (assert '(HasPhysicalQuantity "caesium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "barium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "lanthanum element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "cerium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "praseodymium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "neodymium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "promethium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "samarium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "europium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "gadolinium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "terbium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "dysprosium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "holmium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "erbium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "thulium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "ytterbium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "lutetium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "hafnium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "tantalum element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "tungsten element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "rhenium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "osmium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "iridium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "platinum element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "gold element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "mercury element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "thallium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "lead element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "bismuth element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "polonium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "astatine element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "radon element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "francium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "radium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "actinium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "thorium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "protactinium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "uranium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "neptunium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "plutonium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "americium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "curium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "berkelium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "californium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "einsteinium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "fermium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "mendelevium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "nobelium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "lawrencium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "rutherfordium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "dubnium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "seaborgium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "bohrium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "hassium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "meitnerium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "darmstadtium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "roentgenium  element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "copernicium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "ununtrium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "flerovium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "ununpentium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "livermorium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "ununseptium element*" "relative atomic mass*" ""))
 (assert '(HasPhysicalQuantity "ununoctium element*" "relative atomic mass*" ""))
 
 (assert '(HasUnitaryPhysicalQuantity "hydrogen element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "helium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lithium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "beryllium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "boron element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "carbon element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "nitrogen element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "oxygen element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "fluorine element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "neon element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "sodium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "magnesium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "aluminium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "silicon element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "phosphorus element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "sulfur element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "chlorine element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "argon element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "potassium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "calcium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "scandium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "titanium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "vanadium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "chromium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "manganese  element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "iron element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "cobalt element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "nickel element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "copper element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "zinc element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "gallium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "germanium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "arsenic element*" "semi-metal class"))
 (assert '(HasUnitaryPhysicalQuantity "selenium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "bromine element*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "krypton element*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rubidium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "strontium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "yttrium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "zirconium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "niobium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "molybdenum element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "technetium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ruthenium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rhodium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "palladium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "silver element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "cadmium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "indium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tin element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "antimony element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tellurium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "iodine element*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "xenon element*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "caesium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "barium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lanthanum element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "cerium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "praseodymium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "neodymium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "promethium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "samarium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "europium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "gadolinium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "terbium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "dysprosium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "holmium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "erbium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "thulium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ytterbium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lutetium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "hafnium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tantalum element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tungsten element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rhenium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "osmium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "iridium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "platinum element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "gold element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "mercury element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "thallium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lead element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "bismuth element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "polonium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "astatine element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "radon element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "francium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "radium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "actinium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "thorium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "protactinium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "uranium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "neptunium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "plutonium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "americium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "curium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "berkelium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "californium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "einsteinium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "fermium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "mendelevium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "nobelium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lawrencium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rutherfordium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "dubnium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "seaborgium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "bohrium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "hassium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "meitnerium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "darmstadtium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "roentgenium  element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "copernicium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununtrium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "flerovium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununpentium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "livermorium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununseptium element*" "boiling point*" "" "degree Celsius unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununoctium element*" "boiling point*" "" "degree Celsius unit*"))

 (assert '(HasUnitaryPhysicalQuantity "hydrogen element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "helium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lithium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "beryllium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "boron element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "carbon element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "nitrogen element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "oxygen element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "fluorine element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "neon element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "sodium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "magnesium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "aluminium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "silicon element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "phosphorus element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "sulfur element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "chlorine element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "argon element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "potassium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "calcium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "scandium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "titanium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "vanadium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "chromium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "manganese  element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "iron element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "cobalt element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "nickel element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "copper element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "zinc element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "gallium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "germanium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "arsenic element*" "semi-metal class"))
 (assert '(HasUnitaryPhysicalQuantity "selenium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "bromine element*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "krypton element*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rubidium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "strontium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "yttrium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "zirconium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "niobium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "molybdenum element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "technetium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ruthenium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rhodium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "palladium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "silver element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "cadmium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "indium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tin element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "antimony element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tellurium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "iodine element*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "xenon element*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "caesium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "barium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lanthanum element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "cerium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "praseodymium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "neodymium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "promethium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "samarium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "europium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "gadolinium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "terbium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "dysprosium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "holmium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "erbium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "thulium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ytterbium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lutetium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "hafnium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tantalum element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "tungsten element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rhenium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "osmium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "iridium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "platinum element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "gold element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "mercury element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "thallium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lead element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "bismuth element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "polonium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "astatine element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "radon element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "francium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "radium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "actinium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "thorium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "protactinium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "uranium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "neptunium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "plutonium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "americium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "curium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "berkelium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "californium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "einsteinium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "fermium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "mendelevium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "nobelium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "lawrencium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "rutherfordium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "dubnium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "seaborgium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "bohrium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "hassium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "meitnerium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "darmstadtium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "roentgenium  element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "copernicium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununtrium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "flerovium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununpentium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "livermorium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununseptium element*" "density*" "" "gram per centimetre cubed unit*"))
 (assert '(HasUnitaryPhysicalQuantity "ununoctium element*" "density*" "" "gram per centimetre cubed unit*"))
